// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/spidernet-io/spiderpool/api/v1/agent/server/restapi/connectivity"
	"github.com/spidernet-io/spiderpool/api/v1/agent/server/restapi/daemonset"
	runtimeops "github.com/spidernet-io/spiderpool/api/v1/agent/server/restapi/runtime"
)

// NewSpiderpoolAgentAPIAPI creates a new SpiderpoolAgentAPI instance
func NewSpiderpoolAgentAPIAPI(spec *loads.Document) *SpiderpoolAgentAPIAPI {
	_ = "STUB: not implemented"
	return nil
}

/*SpiderpoolAgentAPIAPI Spiderpool Agent */
type SpiderpoolAgentAPIAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// DaemonsetDeleteIpamIPHandler sets the operation handler for the delete ipam IP operation
	DaemonsetDeleteIpamIPHandler daemonset.DeleteIpamIPHandler
	// DaemonsetDeleteIpamIpsHandler sets the operation handler for the delete ipam ips operation
	DaemonsetDeleteIpamIpsHandler daemonset.DeleteIpamIpsHandler
	// DaemonsetGetCoordinatorConfigHandler sets the operation handler for the get coordinator config operation
	DaemonsetGetCoordinatorConfigHandler daemonset.GetCoordinatorConfigHandler
	// ConnectivityGetIpamHealthyHandler sets the operation handler for the get ipam healthy operation
	ConnectivityGetIpamHealthyHandler connectivity.GetIpamHealthyHandler
	// RuntimeGetRuntimeLivenessHandler sets the operation handler for the get runtime liveness operation
	RuntimeGetRuntimeLivenessHandler runtimeops.GetRuntimeLivenessHandler
	// RuntimeGetRuntimeReadinessHandler sets the operation handler for the get runtime readiness operation
	RuntimeGetRuntimeReadinessHandler runtimeops.GetRuntimeReadinessHandler
	// RuntimeGetRuntimeStartupHandler sets the operation handler for the get runtime startup operation
	RuntimeGetRuntimeStartupHandler runtimeops.GetRuntimeStartupHandler
	// DaemonsetGetWorkloadendpointHandler sets the operation handler for the get workloadendpoint operation
	DaemonsetGetWorkloadendpointHandler daemonset.GetWorkloadendpointHandler
	// DaemonsetPostIpamIPHandler sets the operation handler for the post ipam IP operation
	DaemonsetPostIpamIPHandler daemonset.PostIpamIPHandler
	// DaemonsetPostIpamIpsHandler sets the operation handler for the post ipam ips operation
	DaemonsetPostIpamIpsHandler daemonset.PostIpamIpsHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *SpiderpoolAgentAPIAPI) UseRedoc() { _ = "STUB: not implemented"; return }

// UseSwaggerUI for documentation at /docs
func (o *SpiderpoolAgentAPIAPI) UseSwaggerUI() { _ = "STUB: not implemented"; return }

// SetDefaultProduces sets the default produces media type
func (o *SpiderpoolAgentAPIAPI) SetDefaultProduces(mediaType string) {
	_ = "STUB: not implemented"
	return
}

// SetDefaultConsumes returns the default consumes media type
func (o *SpiderpoolAgentAPIAPI) SetDefaultConsumes(mediaType string) {
	_ = "STUB: not implemented"
	return
}

// SetSpec sets a spec that will be served for the clients.
func (o *SpiderpoolAgentAPIAPI) SetSpec(spec *loads.Document) {
	_ = "STUB: not implemented"

	// DefaultProduces returns the default produces media type
	return
}

func (o *SpiderpoolAgentAPIAPI) DefaultProduces() string { _ = "STUB: not implemented"; return "" }

// DefaultConsumes returns the default consumes media type
func (o *SpiderpoolAgentAPIAPI) DefaultConsumes() string { _ = "STUB: not implemented"; return "" }

// Formats returns the registered string formats
func (o *SpiderpoolAgentAPIAPI) Formats() strfmt.Registry {
	_ = "STUB: not implemented"

	// RegisterFormat registers a custom format validator
	return *new(strfmt.Registry)
}

func (o *SpiderpoolAgentAPIAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	_ = "STUB: not implemented"
	return
}

// Validate validates the registrations in the SpiderpoolAgentAPIAPI
func (o *SpiderpoolAgentAPIAPI) Validate() error { _ = "STUB: not implemented"; return nil }

// ServeErrorFor gets a error handler for a given operation id
func (o *SpiderpoolAgentAPIAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	_ = "STUB: not implemented"
	return nil

	// AuthenticatorsFor gets the authenticators for the specified security schemes
}

func (o *SpiderpoolAgentAPIAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	_ = "STUB: not implemented"

	// Authorizer returns the registered authorizer
	return nil
}

func (o *SpiderpoolAgentAPIAPI) Authorizer() runtime.Authorizer {
	_ = "STUB: not implemented"

	// ConsumersFor gets the consumers for the specified media types.
	// MIME type parameters are ignored here.
	return *new(runtime.Authorizer)
}

func (o *SpiderpoolAgentAPIAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	_ = "STUB: not implemented"
	return nil
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *SpiderpoolAgentAPIAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	_ = "STUB: not implemented"
	return nil
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *SpiderpoolAgentAPIAPI) HandlerFor(method, path string) (http.Handler, bool) {
	_ = "STUB: not implemented"
	return *new(http.Handler), false
}

// Context returns the middleware context for the spiderpool agent API API
func (o *SpiderpoolAgentAPIAPI) Context() *middleware.Context {
	_ = "STUB: not implemented"
	return nil
}

func (o *SpiderpoolAgentAPIAPI) initHandlerCache() {
	_ = "STUB: not implemented"
	// don't care about the result, just that the initialization happened
	return
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *SpiderpoolAgentAPIAPI) Serve(builder middleware.Builder) http.Handler {
	_ = "STUB: not implemented"
	return *new(http.Handler)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *SpiderpoolAgentAPIAPI) Init() { _ = "STUB: not implemented"; return }

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *SpiderpoolAgentAPIAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	_ = "STUB: not implemented"
	return
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *SpiderpoolAgentAPIAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *SpiderpoolAgentAPIAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	_ = "STUB: not implemented"
	return
}
