// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package daemonset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new daemonset API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	_ = "STUB: not implemented"
	return *new(ClientService)
}

/*
Client for daemonset API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	DeleteIpamIP(params *DeleteIpamIPParams, opts ...ClientOption) (*DeleteIpamIPOK, error)

	DeleteIpamIps(params *DeleteIpamIpsParams, opts ...ClientOption) (*DeleteIpamIpsOK, error)

	GetCoordinatorConfig(params *GetCoordinatorConfigParams, opts ...ClientOption) (*GetCoordinatorConfigOK, error)

	GetWorkloadendpoint(params *GetWorkloadendpointParams, opts ...ClientOption) (*GetWorkloadendpointOK, error)

	PostIpamIP(params *PostIpamIPParams, opts ...ClientOption) (*PostIpamIPOK, error)

	PostIpamIps(params *PostIpamIpsParams, opts ...ClientOption) (*PostIpamIpsOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
DeleteIpamIP deletes ip from spiderpool daemon

Send a request to daemonset to ask for an ip deleting
*/
func (a *Client) DeleteIpamIP(params *DeleteIpamIPParams, opts ...ClientOption) (*DeleteIpamIPOK, error) {
	_ = "STUB: not implemented"
	// TODO: Validate the params before sending
	return nil, nil
}

// unexpected success response
// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue

/*
DeleteIpamIps deletes multiple ip as a batch

Delete multiple ip for a pod, case for spiderflat compent
*/
func (a *Client) DeleteIpamIps(params *DeleteIpamIpsParams, opts ...ClientOption) (*DeleteIpamIpsOK, error) {
	_ = "STUB: not implemented"
	// TODO: Validate the params before sending
	return nil, nil
}

// unexpected success response
// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue

/*
GetCoordinatorConfig gets coordinator config

Send a request to daemonset to get coordinator config
*/
func (a *Client) GetCoordinatorConfig(params *GetCoordinatorConfigParams, opts ...ClientOption) (*GetCoordinatorConfigOK, error) {
	_ = "STUB: not implemented"
	// TODO: Validate the params before sending
	return nil, nil
}

// unexpected success response
// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue

/*
	GetWorkloadendpoint gets workloadendpoint status

	Retrieve Pod network allocation details including IP addresses, VLAN IDs, and MAC addresses.

Designed for external systems (e.g., CNI plugins, cloud provider integrations) to query
allocation information via Unix Socket. The `mac` and `vlan` fields are optional and only
included when populated during IP allocation.
*/
func (a *Client) GetWorkloadendpoint(params *GetWorkloadendpointParams, opts ...ClientOption) (*GetWorkloadendpointOK, error) {
	_ = "STUB: not implemented"
	// TODO: Validate the params before sending
	return nil, nil
}

// unexpected success response
// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue

/*
PostIpamIP gets ip from spiderpool daemon

Send a request to daemonset to ask for an ip assignment
*/
func (a *Client) PostIpamIP(params *PostIpamIPParams, opts ...ClientOption) (*PostIpamIPOK, error) {
	_ = "STUB: not implemented"
	// TODO: Validate the params before sending
	return nil, nil
}

// unexpected success response
// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue

/*
PostIpamIps assigns multiple ip as a batch

Assign multiple ip for a pod, case for spiderflat compent
*/
func (a *Client) PostIpamIps(params *PostIpamIpsParams, opts ...ClientOption) (*PostIpamIpsOK, error) {
	_ = "STUB: not implemented"
	// TODO: Validate the params before sending
	return nil, nil
}

// unexpected success response
// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) { _ = "STUB: not implemented"; return }
