// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package daemonset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/spidernet-io/spiderpool/api/v1/agent/models"
)

// DeleteIpamIpsReader is a Reader for the DeleteIpamIps structure.
type DeleteIpamIpsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteIpamIpsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewDeleteIpamIpsOK creates a DeleteIpamIpsOK with default headers values
func NewDeleteIpamIpsOK() *DeleteIpamIpsOK { _ = "STUB: not implemented"; return nil }

/*
DeleteIpamIpsOK describes a response with status code 200, with default header values.

Success
*/
type DeleteIpamIpsOK struct {
}

// IsSuccess returns true when this delete ipam ips o k response has a 2xx status code
func (o *DeleteIpamIpsOK) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this delete ipam ips o k response has a 3xx status code
	return false
}

func (o *DeleteIpamIpsOK) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this delete ipam ips o k response has a 4xx status code
	return false
}

func (o *DeleteIpamIpsOK) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this delete ipam ips o k response has a 5xx status code
	return false
}

func (o *DeleteIpamIpsOK) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this delete ipam ips o k response a status code equal to that given
	return false
}

func (o *DeleteIpamIpsOK) IsCode(code int) bool {
	_ = "STUB: not implemented"

	// Code gets the status code for the delete ipam ips o k response
	return false
}

func (o *DeleteIpamIpsOK) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *DeleteIpamIpsOK) Error() string { _ = "STUB: not implemented"; return "" }

func (o *DeleteIpamIpsOK) String() string { _ = "STUB: not implemented"; return "" }

func (o *DeleteIpamIpsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// NewDeleteIpamIpsFailure creates a DeleteIpamIpsFailure with default headers values
	return nil
}

func NewDeleteIpamIpsFailure() *DeleteIpamIpsFailure { _ = "STUB: not implemented"; return nil }

/*
DeleteIpamIpsFailure describes a response with status code 500, with default header values.

Addresses release failure
*/
type DeleteIpamIpsFailure struct {
	Payload models.Error
}

// IsSuccess returns true when this delete ipam ips failure response has a 2xx status code
func (o *DeleteIpamIpsFailure) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this delete ipam ips failure response has a 3xx status code
	return false
}

func (o *DeleteIpamIpsFailure) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this delete ipam ips failure response has a 4xx status code
	return false
}

func (o *DeleteIpamIpsFailure) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this delete ipam ips failure response has a 5xx status code
	return false
}

func (o *DeleteIpamIpsFailure) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this delete ipam ips failure response a status code equal to that given
	return false
}

func (o *DeleteIpamIpsFailure) IsCode(code int) bool {
	_ = "STUB: not implemented"

	// Code gets the status code for the delete ipam ips failure response
	return false
}

func (o *DeleteIpamIpsFailure) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *DeleteIpamIpsFailure) Error() string { _ = "STUB: not implemented"; return "" }

func (o *DeleteIpamIpsFailure) String() string { _ = "STUB: not implemented"; return "" }

func (o *DeleteIpamIpsFailure) GetPayload() models.Error {
	_ = "STUB: not implemented"
	return *new(models.Error)
}

func (o *DeleteIpamIpsFailure) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}

// NewDeleteIpamIpsStatus521 creates a DeleteIpamIpsStatus521 with default headers values
func NewDeleteIpamIpsStatus521() *DeleteIpamIpsStatus521 { _ = "STUB: not implemented"; return nil }

/*
DeleteIpamIpsStatus521 describes a response with status code 521, with default header values.

Forbid to release IPs for stateless workload
*/
type DeleteIpamIpsStatus521 struct {
	Payload models.Error
}

// IsSuccess returns true when this delete ipam ips status521 response has a 2xx status code
func (o *DeleteIpamIpsStatus521) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this delete ipam ips status521 response has a 3xx status code
	return false
}

func (o *DeleteIpamIpsStatus521) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this delete ipam ips status521 response has a 4xx status code
	return false
}

func (o *DeleteIpamIpsStatus521) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this delete ipam ips status521 response has a 5xx status code
	return false
}

func (o *DeleteIpamIpsStatus521) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this delete ipam ips status521 response a status code equal to that given
	return false
}

func (o *DeleteIpamIpsStatus521) IsCode(code int) bool {
	_ = "STUB: not implemented"

	// Code gets the status code for the delete ipam ips status521 response
	return false
}

func (o *DeleteIpamIpsStatus521) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *DeleteIpamIpsStatus521) Error() string { _ = "STUB: not implemented"; return "" }

func (o *DeleteIpamIpsStatus521) String() string { _ = "STUB: not implemented"; return "" }

func (o *DeleteIpamIpsStatus521) GetPayload() models.Error {
	_ = "STUB: not implemented"
	return *new(models.Error)
}

func (o *DeleteIpamIpsStatus521) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}

// NewDeleteIpamIpsStatus522 creates a DeleteIpamIpsStatus522 with default headers values
func NewDeleteIpamIpsStatus522() *DeleteIpamIpsStatus522 { _ = "STUB: not implemented"; return nil }

/*
DeleteIpamIpsStatus522 describes a response with status code 522, with default header values.

Forbid to release IPs for stateful workload
*/
type DeleteIpamIpsStatus522 struct {
	Payload models.Error
}

// IsSuccess returns true when this delete ipam ips status522 response has a 2xx status code
func (o *DeleteIpamIpsStatus522) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this delete ipam ips status522 response has a 3xx status code
	return false
}

func (o *DeleteIpamIpsStatus522) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this delete ipam ips status522 response has a 4xx status code
	return false
}

func (o *DeleteIpamIpsStatus522) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this delete ipam ips status522 response has a 5xx status code
	return false
}

func (o *DeleteIpamIpsStatus522) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this delete ipam ips status522 response a status code equal to that given
	return false
}

func (o *DeleteIpamIpsStatus522) IsCode(code int) bool {
	_ = "STUB: not implemented"

	// Code gets the status code for the delete ipam ips status522 response
	return false
}

func (o *DeleteIpamIpsStatus522) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *DeleteIpamIpsStatus522) Error() string { _ = "STUB: not implemented"; return "" }

func (o *DeleteIpamIpsStatus522) String() string { _ = "STUB: not implemented"; return "" }

func (o *DeleteIpamIpsStatus522) GetPayload() models.Error {
	_ = "STUB: not implemented"
	return *new(models.Error)
}

func (o *DeleteIpamIpsStatus522) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}
