// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package daemonset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/spidernet-io/spiderpool/api/v1/agent/models"
)

// NewDeleteIpamIPParams creates a new DeleteIpamIPParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteIpamIPParams() *DeleteIpamIPParams { _ = "STUB: not implemented"; return nil }

// NewDeleteIpamIPParamsWithTimeout creates a new DeleteIpamIPParams object
// with the ability to set a timeout on a request.
func NewDeleteIpamIPParamsWithTimeout(timeout time.Duration) *DeleteIpamIPParams {
	_ = "STUB: not implemented"
	return nil
}

// NewDeleteIpamIPParamsWithContext creates a new DeleteIpamIPParams object
// with the ability to set a context for a request.
func NewDeleteIpamIPParamsWithContext(ctx context.Context) *DeleteIpamIPParams {
	_ = "STUB: not implemented"
	return nil
}

// NewDeleteIpamIPParamsWithHTTPClient creates a new DeleteIpamIPParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteIpamIPParamsWithHTTPClient(client *http.Client) *DeleteIpamIPParams {
	_ = "STUB: not implemented"
	return nil
}

/*
DeleteIpamIPParams contains all the parameters to send to the API endpoint

	for the delete ipam IP operation.

	Typically these are written to a http.Request.
*/
type DeleteIpamIPParams struct {

	// IpamDelArgs.
	IpamDelArgs *models.IpamDelArgs

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete ipam IP params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteIpamIPParams) WithDefaults() *DeleteIpamIPParams {
	_ = "STUB: not implemented"
	return nil

	// SetDefaults hydrates default values in the delete ipam IP params (not the query body).
	//
	// All values with no default are reset to their zero value.
}

func (o *DeleteIpamIPParams) SetDefaults() {
	_ = "STUB: not implemented"
	// no default values defined for this parameter
	return
}

// WithTimeout adds the timeout to the delete ipam IP params
func (o *DeleteIpamIPParams) WithTimeout(timeout time.Duration) *DeleteIpamIPParams {
	_ = "STUB: not implemented"
	return nil
}

// SetTimeout adds the timeout to the delete ipam IP params
func (o *DeleteIpamIPParams) SetTimeout(timeout time.Duration) { _ = "STUB: not implemented"; return }

// WithContext adds the context to the delete ipam IP params
func (o *DeleteIpamIPParams) WithContext(ctx context.Context) *DeleteIpamIPParams {
	_ = "STUB: not implemented"
	return nil
}

// SetContext adds the context to the delete ipam IP params
func (o *DeleteIpamIPParams) SetContext(ctx context.Context) {
	_ = "STUB: not implemented"

	// WithHTTPClient adds the HTTPClient to the delete ipam IP params
	return
}

func (o *DeleteIpamIPParams) WithHTTPClient(client *http.Client) *DeleteIpamIPParams {
	_ = "STUB: not implemented"
	return nil
}

// SetHTTPClient adds the HTTPClient to the delete ipam IP params
func (o *DeleteIpamIPParams) SetHTTPClient(client *http.Client) { _ = "STUB: not implemented"; return }

// WithIpamDelArgs adds the ipamDelArgs to the delete ipam IP params
func (o *DeleteIpamIPParams) WithIpamDelArgs(ipamDelArgs *models.IpamDelArgs) *DeleteIpamIPParams {
	_ = "STUB: not implemented"
	return nil
}

// SetIpamDelArgs adds the ipamDelArgs to the delete ipam IP params
func (o *DeleteIpamIPParams) SetIpamDelArgs(ipamDelArgs *models.IpamDelArgs) {
	_ = "STUB: not implemented"
	return
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteIpamIPParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
