// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package daemonset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/spidernet-io/spiderpool/api/v1/agent/models"
)

// NewDeleteIpamIpsParams creates a new DeleteIpamIpsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteIpamIpsParams() *DeleteIpamIpsParams { _ = "STUB: not implemented"; return nil }

// NewDeleteIpamIpsParamsWithTimeout creates a new DeleteIpamIpsParams object
// with the ability to set a timeout on a request.
func NewDeleteIpamIpsParamsWithTimeout(timeout time.Duration) *DeleteIpamIpsParams {
	_ = "STUB: not implemented"
	return nil
}

// NewDeleteIpamIpsParamsWithContext creates a new DeleteIpamIpsParams object
// with the ability to set a context for a request.
func NewDeleteIpamIpsParamsWithContext(ctx context.Context) *DeleteIpamIpsParams {
	_ = "STUB: not implemented"
	return nil
}

// NewDeleteIpamIpsParamsWithHTTPClient creates a new DeleteIpamIpsParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteIpamIpsParamsWithHTTPClient(client *http.Client) *DeleteIpamIpsParams {
	_ = "STUB: not implemented"
	return nil
}

/*
DeleteIpamIpsParams contains all the parameters to send to the API endpoint

	for the delete ipam ips operation.

	Typically these are written to a http.Request.
*/
type DeleteIpamIpsParams struct {

	// IpamBatchDelArgs.
	IpamBatchDelArgs *models.IpamBatchDelArgs

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete ipam ips params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteIpamIpsParams) WithDefaults() *DeleteIpamIpsParams {
	_ = "STUB: not implemented"
	return nil

	// SetDefaults hydrates default values in the delete ipam ips params (not the query body).
	//
	// All values with no default are reset to their zero value.
}

func (o *DeleteIpamIpsParams) SetDefaults() {
	_ = "STUB: not implemented"
	// no default values defined for this parameter
	return
}

// WithTimeout adds the timeout to the delete ipam ips params
func (o *DeleteIpamIpsParams) WithTimeout(timeout time.Duration) *DeleteIpamIpsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetTimeout adds the timeout to the delete ipam ips params
func (o *DeleteIpamIpsParams) SetTimeout(timeout time.Duration) { _ = "STUB: not implemented"; return }

// WithContext adds the context to the delete ipam ips params
func (o *DeleteIpamIpsParams) WithContext(ctx context.Context) *DeleteIpamIpsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetContext adds the context to the delete ipam ips params
func (o *DeleteIpamIpsParams) SetContext(ctx context.Context) {
	_ = "STUB: not implemented"

	// WithHTTPClient adds the HTTPClient to the delete ipam ips params
	return
}

func (o *DeleteIpamIpsParams) WithHTTPClient(client *http.Client) *DeleteIpamIpsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetHTTPClient adds the HTTPClient to the delete ipam ips params
func (o *DeleteIpamIpsParams) SetHTTPClient(client *http.Client) { _ = "STUB: not implemented"; return }

// WithIpamBatchDelArgs adds the ipamBatchDelArgs to the delete ipam ips params
func (o *DeleteIpamIpsParams) WithIpamBatchDelArgs(ipamBatchDelArgs *models.IpamBatchDelArgs) *DeleteIpamIpsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetIpamBatchDelArgs adds the ipamBatchDelArgs to the delete ipam ips params
func (o *DeleteIpamIpsParams) SetIpamBatchDelArgs(ipamBatchDelArgs *models.IpamBatchDelArgs) {
	_ = "STUB: not implemented"
	return
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteIpamIpsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
