// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package daemonset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/spidernet-io/spiderpool/api/v1/agent/models"
)

// DeleteIpamIPReader is a Reader for the DeleteIpamIP structure.
type DeleteIpamIPReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteIpamIPReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewDeleteIpamIPOK creates a DeleteIpamIPOK with default headers values
func NewDeleteIpamIPOK() *DeleteIpamIPOK { _ = "STUB: not implemented"; return nil }

/*
DeleteIpamIPOK describes a response with status code 200, with default header values.

Success
*/
type DeleteIpamIPOK struct {
}

// IsSuccess returns true when this delete ipam Ip o k response has a 2xx status code
func (o *DeleteIpamIPOK) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this delete ipam Ip o k response has a 3xx status code
	return false
}

func (o *DeleteIpamIPOK) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this delete ipam Ip o k response has a 4xx status code
	return false
}

func (o *DeleteIpamIPOK) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this delete ipam Ip o k response has a 5xx status code
	return false
}

func (o *DeleteIpamIPOK) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this delete ipam Ip o k response a status code equal to that given
	return false
}

func (o *DeleteIpamIPOK) IsCode(code int) bool {
	_ = "STUB: not implemented"

	// Code gets the status code for the delete ipam Ip o k response
	return false
}

func (o *DeleteIpamIPOK) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *DeleteIpamIPOK) Error() string { _ = "STUB: not implemented"; return "" }

func (o *DeleteIpamIPOK) String() string { _ = "STUB: not implemented"; return "" }

func (o *DeleteIpamIPOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// NewDeleteIpamIPFailure creates a DeleteIpamIPFailure with default headers values
	return nil
}

func NewDeleteIpamIPFailure() *DeleteIpamIPFailure { _ = "STUB: not implemented"; return nil }

/*
DeleteIpamIPFailure describes a response with status code 500, with default header values.

Addresses release failure
*/
type DeleteIpamIPFailure struct {
	Payload models.Error
}

// IsSuccess returns true when this delete ipam Ip failure response has a 2xx status code
func (o *DeleteIpamIPFailure) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this delete ipam Ip failure response has a 3xx status code
	return false
}

func (o *DeleteIpamIPFailure) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this delete ipam Ip failure response has a 4xx status code
	return false
}

func (o *DeleteIpamIPFailure) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this delete ipam Ip failure response has a 5xx status code
	return false
}

func (o *DeleteIpamIPFailure) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this delete ipam Ip failure response a status code equal to that given
	return false
}

func (o *DeleteIpamIPFailure) IsCode(code int) bool {
	_ = "STUB: not implemented"

	// Code gets the status code for the delete ipam Ip failure response
	return false
}

func (o *DeleteIpamIPFailure) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *DeleteIpamIPFailure) Error() string { _ = "STUB: not implemented"; return "" }

func (o *DeleteIpamIPFailure) String() string { _ = "STUB: not implemented"; return "" }

func (o *DeleteIpamIPFailure) GetPayload() models.Error {
	_ = "STUB: not implemented"
	return *new(models.Error)
}

func (o *DeleteIpamIPFailure) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}
