// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package daemonset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/spidernet-io/spiderpool/api/v1/agent/models"
)

// NewGetCoordinatorConfigParams creates a new GetCoordinatorConfigParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCoordinatorConfigParams() *GetCoordinatorConfigParams {
	_ = "STUB: not implemented"
	return nil
}

// NewGetCoordinatorConfigParamsWithTimeout creates a new GetCoordinatorConfigParams object
// with the ability to set a timeout on a request.
func NewGetCoordinatorConfigParamsWithTimeout(timeout time.Duration) *GetCoordinatorConfigParams {
	_ = "STUB: not implemented"
	return nil
}

// NewGetCoordinatorConfigParamsWithContext creates a new GetCoordinatorConfigParams object
// with the ability to set a context for a request.
func NewGetCoordinatorConfigParamsWithContext(ctx context.Context) *GetCoordinatorConfigParams {
	_ = "STUB: not implemented"
	return nil
}

// NewGetCoordinatorConfigParamsWithHTTPClient creates a new GetCoordinatorConfigParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCoordinatorConfigParamsWithHTTPClient(client *http.Client) *GetCoordinatorConfigParams {
	_ = "STUB: not implemented"
	return nil
}

/*
GetCoordinatorConfigParams contains all the parameters to send to the API endpoint

	for the get coordinator config operation.

	Typically these are written to a http.Request.
*/
type GetCoordinatorConfigParams struct {

	// GetCoordinatorConfig.
	GetCoordinatorConfig *models.GetCoordinatorArgs

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get coordinator config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCoordinatorConfigParams) WithDefaults() *GetCoordinatorConfigParams {
	_ = "STUB: not implemented"
	return nil

	// SetDefaults hydrates default values in the get coordinator config params (not the query body).
	//
	// All values with no default are reset to their zero value.
}

func (o *GetCoordinatorConfigParams) SetDefaults() {
	_ = "STUB: not implemented"
	// no default values defined for this parameter
	return
}

// WithTimeout adds the timeout to the get coordinator config params
func (o *GetCoordinatorConfigParams) WithTimeout(timeout time.Duration) *GetCoordinatorConfigParams {
	_ = "STUB: not implemented"
	return nil
}

// SetTimeout adds the timeout to the get coordinator config params
func (o *GetCoordinatorConfigParams) SetTimeout(timeout time.Duration) {
	_ = "STUB: not implemented"
	return

	// WithContext adds the context to the get coordinator config params
}

func (o *GetCoordinatorConfigParams) WithContext(ctx context.Context) *GetCoordinatorConfigParams {
	_ = "STUB: not implemented"
	return nil
}

// SetContext adds the context to the get coordinator config params
func (o *GetCoordinatorConfigParams) SetContext(ctx context.Context) {
	_ = "STUB: not implemented"

	// WithHTTPClient adds the HTTPClient to the get coordinator config params
	return
}

func (o *GetCoordinatorConfigParams) WithHTTPClient(client *http.Client) *GetCoordinatorConfigParams {
	_ = "STUB: not implemented"
	return nil
}

// SetHTTPClient adds the HTTPClient to the get coordinator config params
func (o *GetCoordinatorConfigParams) SetHTTPClient(client *http.Client) {
	_ = "STUB: not implemented"
	return

	// WithGetCoordinatorConfig adds the getCoordinatorConfig to the get coordinator config params
}

func (o *GetCoordinatorConfigParams) WithGetCoordinatorConfig(getCoordinatorConfig *models.GetCoordinatorArgs) *GetCoordinatorConfigParams {
	_ = "STUB: not implemented"
	return nil
}

// SetGetCoordinatorConfig adds the getCoordinatorConfig to the get coordinator config params
func (o *GetCoordinatorConfigParams) SetGetCoordinatorConfig(getCoordinatorConfig *models.GetCoordinatorArgs) {
	_ = "STUB: not implemented"
	return
}

// WriteToRequest writes these params to a swagger request
func (o *GetCoordinatorConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
