// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package daemonset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/spidernet-io/spiderpool/api/v1/agent/models"
)

// GetWorkloadendpointReader is a Reader for the GetWorkloadendpoint structure.
type GetWorkloadendpointReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetWorkloadendpointReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewGetWorkloadendpointOK creates a GetWorkloadendpointOK with default headers values
func NewGetWorkloadendpointOK() *GetWorkloadendpointOK { _ = "STUB: not implemented"; return nil }

/*
GetWorkloadendpointOK describes a response with status code 200, with default header values.

Success
*/
type GetWorkloadendpointOK struct {
	Payload *models.WorkloadEndpointStatus
}

// IsSuccess returns true when this get workloadendpoint o k response has a 2xx status code
func (o *GetWorkloadendpointOK) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this get workloadendpoint o k response has a 3xx status code
	return false
}

func (o *GetWorkloadendpointOK) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this get workloadendpoint o k response has a 4xx status code
	return false
}

func (o *GetWorkloadendpointOK) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this get workloadendpoint o k response has a 5xx status code
	return false
}

func (o *GetWorkloadendpointOK) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this get workloadendpoint o k response a status code equal to that given
	return false
}

func (o *GetWorkloadendpointOK) IsCode(code int) bool {
	_ = "STUB: not implemented"

	// Code gets the status code for the get workloadendpoint o k response
	return false
}

func (o *GetWorkloadendpointOK) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *GetWorkloadendpointOK) Error() string { _ = "STUB: not implemented"; return "" }

func (o *GetWorkloadendpointOK) String() string { _ = "STUB: not implemented"; return "" }

func (o *GetWorkloadendpointOK) GetPayload() *models.WorkloadEndpointStatus {
	_ = "STUB: not implemented"
	return nil
}

func (o *GetWorkloadendpointOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// response payload

// NewGetWorkloadendpointBadRequest creates a GetWorkloadendpointBadRequest with default headers values
func NewGetWorkloadendpointBadRequest() *GetWorkloadendpointBadRequest {
	_ = "STUB: not implemented"
	return nil
}

/*
GetWorkloadendpointBadRequest describes a response with status code 400, with default header values.

Missing or invalid parameters
*/
type GetWorkloadendpointBadRequest struct {
	Payload models.Error
}

// IsSuccess returns true when this get workloadendpoint bad request response has a 2xx status code
func (o *GetWorkloadendpointBadRequest) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this get workloadendpoint bad request response has a 3xx status code
	return false
}

func (o *GetWorkloadendpointBadRequest) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this get workloadendpoint bad request response has a 4xx status code
	return false
}

func (o *GetWorkloadendpointBadRequest) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this get workloadendpoint bad request response has a 5xx status code
	return false
}

func (o *GetWorkloadendpointBadRequest) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this get workloadendpoint bad request response a status code equal to that given
	return false
}

func (o *GetWorkloadendpointBadRequest) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the get workloadendpoint bad request response
}

func (o *GetWorkloadendpointBadRequest) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *GetWorkloadendpointBadRequest) Error() string { _ = "STUB: not implemented"; return "" }

func (o *GetWorkloadendpointBadRequest) String() string { _ = "STUB: not implemented"; return "" }

func (o *GetWorkloadendpointBadRequest) GetPayload() models.Error {
	_ = "STUB: not implemented"
	return *new(models.Error)
}

func (o *GetWorkloadendpointBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}

// NewGetWorkloadendpointNotFound creates a GetWorkloadendpointNotFound with default headers values
func NewGetWorkloadendpointNotFound() *GetWorkloadendpointNotFound {
	_ = "STUB: not implemented"
	return nil
}

/*
GetWorkloadendpointNotFound describes a response with status code 404, with default header values.

SpiderEndpoint not found for specified Pod
*/
type GetWorkloadendpointNotFound struct {
	Payload models.Error
}

// IsSuccess returns true when this get workloadendpoint not found response has a 2xx status code
func (o *GetWorkloadendpointNotFound) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this get workloadendpoint not found response has a 3xx status code
	return false
}

func (o *GetWorkloadendpointNotFound) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this get workloadendpoint not found response has a 4xx status code
	return false
}

func (o *GetWorkloadendpointNotFound) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this get workloadendpoint not found response has a 5xx status code
	return false
}

func (o *GetWorkloadendpointNotFound) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this get workloadendpoint not found response a status code equal to that given
	return false
}

func (o *GetWorkloadendpointNotFound) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the get workloadendpoint not found response
}

func (o *GetWorkloadendpointNotFound) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *GetWorkloadendpointNotFound) Error() string { _ = "STUB: not implemented"; return "" }

func (o *GetWorkloadendpointNotFound) String() string { _ = "STUB: not implemented"; return "" }

func (o *GetWorkloadendpointNotFound) GetPayload() models.Error {
	_ = "STUB: not implemented"
	return *new(models.Error)
}

func (o *GetWorkloadendpointNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}

// NewGetWorkloadendpointInternalServerError creates a GetWorkloadendpointInternalServerError with default headers values
func NewGetWorkloadendpointInternalServerError() *GetWorkloadendpointInternalServerError {
	_ = "STUB: not implemented"
	return nil
}

/*
GetWorkloadendpointInternalServerError describes a response with status code 500, with default header values.

Get workloadendpoint failure
*/
type GetWorkloadendpointInternalServerError struct {
	Payload models.Error
}

// IsSuccess returns true when this get workloadendpoint internal server error response has a 2xx status code
func (o *GetWorkloadendpointInternalServerError) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this get workloadendpoint internal server error response has a 3xx status code
	return false
}

func (o *GetWorkloadendpointInternalServerError) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this get workloadendpoint internal server error response has a 4xx status code
	return false
}

func (o *GetWorkloadendpointInternalServerError) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this get workloadendpoint internal server error response has a 5xx status code
	return false
}

func (o *GetWorkloadendpointInternalServerError) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this get workloadendpoint internal server error response a status code equal to that given
	return false
}

func (o *GetWorkloadendpointInternalServerError) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the get workloadendpoint internal server error response
}

func (o *GetWorkloadendpointInternalServerError) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *GetWorkloadendpointInternalServerError) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *GetWorkloadendpointInternalServerError) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *GetWorkloadendpointInternalServerError) GetPayload() models.Error {
	_ = "STUB: not implemented"
	return *new(models.Error)
}

func (o *GetWorkloadendpointInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}
