// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package daemonset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// NewGetWorkloadendpointParams creates a new GetWorkloadendpointParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetWorkloadendpointParams() *GetWorkloadendpointParams {
	_ = "STUB: not implemented"
	return nil
}

// NewGetWorkloadendpointParamsWithTimeout creates a new GetWorkloadendpointParams object
// with the ability to set a timeout on a request.
func NewGetWorkloadendpointParamsWithTimeout(timeout time.Duration) *GetWorkloadendpointParams {
	_ = "STUB: not implemented"
	return nil
}

// NewGetWorkloadendpointParamsWithContext creates a new GetWorkloadendpointParams object
// with the ability to set a context for a request.
func NewGetWorkloadendpointParamsWithContext(ctx context.Context) *GetWorkloadendpointParams {
	_ = "STUB: not implemented"
	return nil
}

// NewGetWorkloadendpointParamsWithHTTPClient creates a new GetWorkloadendpointParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetWorkloadendpointParamsWithHTTPClient(client *http.Client) *GetWorkloadendpointParams {
	_ = "STUB: not implemented"
	return nil
}

/*
GetWorkloadendpointParams contains all the parameters to send to the API endpoint

	for the get workloadendpoint operation.

	Typically these are written to a http.Request.
*/
type GetWorkloadendpointParams struct {

	/* PodName.

	   Pod name
	*/
	PodName string

	/* PodNamespace.

	   Pod namespace
	*/
	PodNamespace string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get workloadendpoint params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetWorkloadendpointParams) WithDefaults() *GetWorkloadendpointParams {
	_ = "STUB: not implemented"
	return nil

	// SetDefaults hydrates default values in the get workloadendpoint params (not the query body).
	//
	// All values with no default are reset to their zero value.
}

func (o *GetWorkloadendpointParams) SetDefaults() {
	_ = "STUB: not implemented"
	// no default values defined for this parameter
	return
}

// WithTimeout adds the timeout to the get workloadendpoint params
func (o *GetWorkloadendpointParams) WithTimeout(timeout time.Duration) *GetWorkloadendpointParams {
	_ = "STUB: not implemented"
	return nil
}

// SetTimeout adds the timeout to the get workloadendpoint params
func (o *GetWorkloadendpointParams) SetTimeout(timeout time.Duration) {
	_ = "STUB: not implemented"
	return

	// WithContext adds the context to the get workloadendpoint params
}

func (o *GetWorkloadendpointParams) WithContext(ctx context.Context) *GetWorkloadendpointParams {
	_ = "STUB: not implemented"
	return nil
}

// SetContext adds the context to the get workloadendpoint params
func (o *GetWorkloadendpointParams) SetContext(ctx context.Context) {
	_ = "STUB: not implemented"

	// WithHTTPClient adds the HTTPClient to the get workloadendpoint params
	return
}

func (o *GetWorkloadendpointParams) WithHTTPClient(client *http.Client) *GetWorkloadendpointParams {
	_ = "STUB: not implemented"
	return nil
}

// SetHTTPClient adds the HTTPClient to the get workloadendpoint params
func (o *GetWorkloadendpointParams) SetHTTPClient(client *http.Client) {
	_ = "STUB: not implemented"
	return

	// WithPodName adds the podName to the get workloadendpoint params
}

func (o *GetWorkloadendpointParams) WithPodName(podName string) *GetWorkloadendpointParams {
	_ = "STUB: not implemented"
	return nil
}

// SetPodName adds the podName to the get workloadendpoint params
func (o *GetWorkloadendpointParams) SetPodName(podName string) { _ = "STUB: not implemented"; return }

// WithPodNamespace adds the podNamespace to the get workloadendpoint params
func (o *GetWorkloadendpointParams) WithPodNamespace(podNamespace string) *GetWorkloadendpointParams {
	_ = "STUB: not implemented"
	return nil
}

// SetPodNamespace adds the podNamespace to the get workloadendpoint params
func (o *GetWorkloadendpointParams) SetPodNamespace(podNamespace string) {
	_ = "STUB: not implemented"
	return
}

// WriteToRequest writes these params to a swagger request
func (o *GetWorkloadendpointParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// query param podName

// query param podNamespace
