// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package daemonset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/spidernet-io/spiderpool/api/v1/agent/models"
)

// GetCoordinatorConfigReader is a Reader for the GetCoordinatorConfig structure.
type GetCoordinatorConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCoordinatorConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewGetCoordinatorConfigOK creates a GetCoordinatorConfigOK with default headers values
func NewGetCoordinatorConfigOK() *GetCoordinatorConfigOK { _ = "STUB: not implemented"; return nil }

/*
GetCoordinatorConfigOK describes a response with status code 200, with default header values.

Success
*/
type GetCoordinatorConfigOK struct {
	Payload *models.CoordinatorConfig
}

// IsSuccess returns true when this get coordinator config o k response has a 2xx status code
func (o *GetCoordinatorConfigOK) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this get coordinator config o k response has a 3xx status code
	return false
}

func (o *GetCoordinatorConfigOK) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this get coordinator config o k response has a 4xx status code
	return false
}

func (o *GetCoordinatorConfigOK) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this get coordinator config o k response has a 5xx status code
	return false
}

func (o *GetCoordinatorConfigOK) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this get coordinator config o k response a status code equal to that given
	return false
}

func (o *GetCoordinatorConfigOK) IsCode(code int) bool {
	_ = "STUB: not implemented"

	// Code gets the status code for the get coordinator config o k response
	return false
}

func (o *GetCoordinatorConfigOK) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *GetCoordinatorConfigOK) Error() string { _ = "STUB: not implemented"; return "" }

func (o *GetCoordinatorConfigOK) String() string { _ = "STUB: not implemented"; return "" }

func (o *GetCoordinatorConfigOK) GetPayload() *models.CoordinatorConfig {
	_ = "STUB: not implemented"
	return nil
}

func (o *GetCoordinatorConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// response payload

// NewGetCoordinatorConfigFailure creates a GetCoordinatorConfigFailure with default headers values
func NewGetCoordinatorConfigFailure() *GetCoordinatorConfigFailure {
	_ = "STUB: not implemented"
	return nil
}

/*
GetCoordinatorConfigFailure describes a response with status code 500, with default header values.

Config not initialized successfully or others
*/
type GetCoordinatorConfigFailure struct {
	Payload models.Error
}

// IsSuccess returns true when this get coordinator config failure response has a 2xx status code
func (o *GetCoordinatorConfigFailure) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this get coordinator config failure response has a 3xx status code
	return false
}

func (o *GetCoordinatorConfigFailure) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this get coordinator config failure response has a 4xx status code
	return false
}

func (o *GetCoordinatorConfigFailure) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this get coordinator config failure response has a 5xx status code
	return false
}

func (o *GetCoordinatorConfigFailure) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this get coordinator config failure response a status code equal to that given
	return false
}

func (o *GetCoordinatorConfigFailure) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the get coordinator config failure response
}

func (o *GetCoordinatorConfigFailure) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *GetCoordinatorConfigFailure) Error() string { _ = "STUB: not implemented"; return "" }

func (o *GetCoordinatorConfigFailure) String() string { _ = "STUB: not implemented"; return "" }

func (o *GetCoordinatorConfigFailure) GetPayload() models.Error {
	_ = "STUB: not implemented"
	return *new(models.Error)
}

func (o *GetCoordinatorConfigFailure) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}
