// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package daemonset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// NewPostIpamIpsParams creates a new PostIpamIpsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostIpamIpsParams() *PostIpamIpsParams { _ = "STUB: not implemented"; return nil }

// NewPostIpamIpsParamsWithTimeout creates a new PostIpamIpsParams object
// with the ability to set a timeout on a request.
func NewPostIpamIpsParamsWithTimeout(timeout time.Duration) *PostIpamIpsParams {
	_ = "STUB: not implemented"
	return nil
}

// NewPostIpamIpsParamsWithContext creates a new PostIpamIpsParams object
// with the ability to set a context for a request.
func NewPostIpamIpsParamsWithContext(ctx context.Context) *PostIpamIpsParams {
	_ = "STUB: not implemented"
	return nil
}

// NewPostIpamIpsParamsWithHTTPClient creates a new PostIpamIpsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostIpamIpsParamsWithHTTPClient(client *http.Client) *PostIpamIpsParams {
	_ = "STUB: not implemented"
	return nil
}

/*
PostIpamIpsParams contains all the parameters to send to the API endpoint

	for the post ipam ips operation.

	Typically these are written to a http.Request.
*/
type PostIpamIpsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post ipam ips params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostIpamIpsParams) WithDefaults() *PostIpamIpsParams {
	_ = "STUB: not implemented"
	return nil

	// SetDefaults hydrates default values in the post ipam ips params (not the query body).
	//
	// All values with no default are reset to their zero value.
}

func (o *PostIpamIpsParams) SetDefaults() {
	_ = "STUB: not implemented"
	// no default values defined for this parameter
	return
}

// WithTimeout adds the timeout to the post ipam ips params
func (o *PostIpamIpsParams) WithTimeout(timeout time.Duration) *PostIpamIpsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetTimeout adds the timeout to the post ipam ips params
func (o *PostIpamIpsParams) SetTimeout(timeout time.Duration) { _ = "STUB: not implemented"; return }

// WithContext adds the context to the post ipam ips params
func (o *PostIpamIpsParams) WithContext(ctx context.Context) *PostIpamIpsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetContext adds the context to the post ipam ips params
func (o *PostIpamIpsParams) SetContext(ctx context.Context) {
	_ = "STUB: not implemented"

	// WithHTTPClient adds the HTTPClient to the post ipam ips params
	return
}

func (o *PostIpamIpsParams) WithHTTPClient(client *http.Client) *PostIpamIpsParams {
	_ = "STUB: not implemented"
	return nil
}

// SetHTTPClient adds the HTTPClient to the post ipam ips params
func (o *PostIpamIpsParams) SetHTTPClient(client *http.Client) { _ = "STUB: not implemented"; return }

// WriteToRequest writes these params to a swagger request
func (o *PostIpamIpsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
