// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package daemonset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/spidernet-io/spiderpool/api/v1/agent/models"
)

// PostIpamIpsReader is a Reader for the PostIpamIps structure.
type PostIpamIpsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostIpamIpsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewPostIpamIpsOK creates a PostIpamIpsOK with default headers values
func NewPostIpamIpsOK() *PostIpamIpsOK { _ = "STUB: not implemented"; return nil }

/*
PostIpamIpsOK describes a response with status code 200, with default header values.

Success
*/
type PostIpamIpsOK struct {
}

// IsSuccess returns true when this post ipam ips o k response has a 2xx status code
func (o *PostIpamIpsOK) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this post ipam ips o k response has a 3xx status code
	return false
}

func (o *PostIpamIpsOK) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this post ipam ips o k response has a 4xx status code
	return false
}

func (o *PostIpamIpsOK) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this post ipam ips o k response has a 5xx status code
	return false
}

func (o *PostIpamIpsOK) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this post ipam ips o k response a status code equal to that given
	return false
}

func (o *PostIpamIpsOK) IsCode(code int) bool {
	_ = "STUB: not implemented"

	// Code gets the status code for the post ipam ips o k response
	return false
}

func (o *PostIpamIpsOK) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *PostIpamIpsOK) Error() string { _ = "STUB: not implemented"; return "" }

func (o *PostIpamIpsOK) String() string { _ = "STUB: not implemented"; return "" }

func (o *PostIpamIpsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// NewPostIpamIpsFailure creates a PostIpamIpsFailure with default headers values
	return nil
}

func NewPostIpamIpsFailure() *PostIpamIpsFailure { _ = "STUB: not implemented"; return nil }

/*
PostIpamIpsFailure describes a response with status code 500, with default header values.

Allocation failure
*/
type PostIpamIpsFailure struct {
	Payload models.Error
}

// IsSuccess returns true when this post ipam ips failure response has a 2xx status code
func (o *PostIpamIpsFailure) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this post ipam ips failure response has a 3xx status code
	return false
}

func (o *PostIpamIpsFailure) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this post ipam ips failure response has a 4xx status code
	return false
}

func (o *PostIpamIpsFailure) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this post ipam ips failure response has a 5xx status code
	return false
}

func (o *PostIpamIpsFailure) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this post ipam ips failure response a status code equal to that given
	return false
}

func (o *PostIpamIpsFailure) IsCode(code int) bool {
	_ = "STUB: not implemented"

	// Code gets the status code for the post ipam ips failure response
	return false
}

func (o *PostIpamIpsFailure) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *PostIpamIpsFailure) Error() string { _ = "STUB: not implemented"; return "" }

func (o *PostIpamIpsFailure) String() string { _ = "STUB: not implemented"; return "" }

func (o *PostIpamIpsFailure) GetPayload() models.Error {
	_ = "STUB: not implemented"
	return *new(models.Error)
}

func (o *PostIpamIpsFailure) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}
