// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package daemonset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/spidernet-io/spiderpool/api/v1/agent/models"
)

// PostIpamIPReader is a Reader for the PostIpamIP structure.
type PostIpamIPReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostIpamIPReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewPostIpamIPOK creates a PostIpamIPOK with default headers values
func NewPostIpamIPOK() *PostIpamIPOK { _ = "STUB: not implemented"; return nil }

/*
PostIpamIPOK describes a response with status code 200, with default header values.

Success
*/
type PostIpamIPOK struct {
	Payload *models.IpamAddResponse
}

// IsSuccess returns true when this post ipam Ip o k response has a 2xx status code
func (o *PostIpamIPOK) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this post ipam Ip o k response has a 3xx status code
	return false
}

func (o *PostIpamIPOK) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this post ipam Ip o k response has a 4xx status code
	return false
}

func (o *PostIpamIPOK) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this post ipam Ip o k response has a 5xx status code
	return false
}

func (o *PostIpamIPOK) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this post ipam Ip o k response a status code equal to that given
	return false
}

func (o *PostIpamIPOK) IsCode(code int) bool {
	_ = "STUB: not implemented"

	// Code gets the status code for the post ipam Ip o k response
	return false
}

func (o *PostIpamIPOK) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *PostIpamIPOK) Error() string { _ = "STUB: not implemented"; return "" }

func (o *PostIpamIPOK) String() string { _ = "STUB: not implemented"; return "" }

func (o *PostIpamIPOK) GetPayload() *models.IpamAddResponse { _ = "STUB: not implemented"; return nil }

func (o *PostIpamIPOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// response payload

// NewPostIpamIPFailure creates a PostIpamIPFailure with default headers values
func NewPostIpamIPFailure() *PostIpamIPFailure { _ = "STUB: not implemented"; return nil }

/*
PostIpamIPFailure describes a response with status code 500, with default header values.

Allocation failure
*/
type PostIpamIPFailure struct {
	Payload models.Error
}

// IsSuccess returns true when this post ipam Ip failure response has a 2xx status code
func (o *PostIpamIPFailure) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this post ipam Ip failure response has a 3xx status code
	return false
}

func (o *PostIpamIPFailure) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this post ipam Ip failure response has a 4xx status code
	return false
}

func (o *PostIpamIPFailure) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this post ipam Ip failure response has a 5xx status code
	return false
}

func (o *PostIpamIPFailure) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this post ipam Ip failure response a status code equal to that given
	return false
}

func (o *PostIpamIPFailure) IsCode(code int) bool {
	_ = "STUB: not implemented"

	// Code gets the status code for the post ipam Ip failure response
	return false
}

func (o *PostIpamIPFailure) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *PostIpamIPFailure) Error() string { _ = "STUB: not implemented"; return "" }

func (o *PostIpamIPFailure) String() string { _ = "STUB: not implemented"; return "" }

func (o *PostIpamIPFailure) GetPayload() models.Error {
	_ = "STUB: not implemented"
	return *new(models.Error)
}

func (o *PostIpamIPFailure) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// response payload
	return nil
}
