// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v2beta1 "github.com/spidernet-io/spiderpool/pkg/k8s/apis/spiderpool.spidernet.io/v2beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
)

// FakeSpiderMultusConfigs implements SpiderMultusConfigInterface
type FakeSpiderMultusConfigs struct {
	Fake *FakeSpiderpoolV2beta1
	ns   string
}

var spidermultusconfigsResource = v2beta1.SchemeGroupVersion.WithResource("spidermultusconfigs")

var spidermultusconfigsKind = v2beta1.SchemeGroupVersion.WithKind("SpiderMultusConfig")

// Get takes name of the spiderMultusConfig, and returns the corresponding spiderMultusConfig object, and an error if there is any.
func (c *FakeSpiderMultusConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2beta1.SpiderMultusConfig, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// List takes label and field selectors, and returns the list of SpiderMultusConfigs that match those selectors.
func (c *FakeSpiderMultusConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v2beta1.SpiderMultusConfigList, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Watch returns a watch.Interface that watches the requested spiderMultusConfigs.
func (c *FakeSpiderMultusConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	_ = "STUB: not implemented"
	return *new(watch.Interface), nil
}

// Create takes the representation of a spiderMultusConfig and creates it.  Returns the server's representation of the spiderMultusConfig, and an error, if there is any.
func (c *FakeSpiderMultusConfigs) Create(ctx context.Context, spiderMultusConfig *v2beta1.SpiderMultusConfig, opts v1.CreateOptions) (result *v2beta1.SpiderMultusConfig, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Update takes the representation of a spiderMultusConfig and updates it. Returns the server's representation of the spiderMultusConfig, and an error, if there is any.
func (c *FakeSpiderMultusConfigs) Update(ctx context.Context, spiderMultusConfig *v2beta1.SpiderMultusConfig, opts v1.UpdateOptions) (result *v2beta1.SpiderMultusConfig, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Delete takes name of the spiderMultusConfig and deletes it. Returns an error if one occurs.
func (c *FakeSpiderMultusConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSpiderMultusConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// Patch applies the patch and returns the patched spiderMultusConfig.
func (c *FakeSpiderMultusConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2beta1.SpiderMultusConfig, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}
