// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2beta1 "github.com/spidernet-io/spiderpool/pkg/k8s/client/clientset/versioned/typed/spiderpool.spidernet.io/v2beta1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeSpiderpoolV2beta1 struct {
	*testing.Fake
}

func (c *FakeSpiderpoolV2beta1) SpiderCoordinators() v2beta1.SpiderCoordinatorInterface {
	_ = "STUB: not implemented"
	return *new(v2beta1.SpiderCoordinatorInterface)
}

func (c *FakeSpiderpoolV2beta1) SpiderIPPools() v2beta1.SpiderIPPoolInterface {
	_ = "STUB: not implemented"
	return *new(v2beta1.SpiderIPPoolInterface)
}

func (c *FakeSpiderpoolV2beta1) SpiderMultusConfigs(namespace string) v2beta1.SpiderMultusConfigInterface {
	_ = "STUB: not implemented"
	return *new(v2beta1.SpiderMultusConfigInterface)
}

func (c *FakeSpiderpoolV2beta1) SpiderSubnets() v2beta1.SpiderSubnetInterface {
	_ = "STUB: not implemented"
	return *new(v2beta1.SpiderSubnetInterface)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeSpiderpoolV2beta1) RESTClient() rest.Interface {
	_ = "STUB: not implemented"
	return *new(rest.Interface)
}
