// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v2beta1 "github.com/spidernet-io/spiderpool/pkg/k8s/apis/spiderpool.spidernet.io/v2beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
)

// FakeSpiderCoordinators implements SpiderCoordinatorInterface
type FakeSpiderCoordinators struct {
	Fake *FakeSpiderpoolV2beta1
}

var spidercoordinatorsResource = v2beta1.SchemeGroupVersion.WithResource("spidercoordinators")

var spidercoordinatorsKind = v2beta1.SchemeGroupVersion.WithKind("SpiderCoordinator")

// Get takes name of the spiderCoordinator, and returns the corresponding spiderCoordinator object, and an error if there is any.
func (c *FakeSpiderCoordinators) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2beta1.SpiderCoordinator, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// List takes label and field selectors, and returns the list of SpiderCoordinators that match those selectors.
func (c *FakeSpiderCoordinators) List(ctx context.Context, opts v1.ListOptions) (result *v2beta1.SpiderCoordinatorList, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Watch returns a watch.Interface that watches the requested spiderCoordinators.
func (c *FakeSpiderCoordinators) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	_ = "STUB: not implemented"
	return *new(watch.Interface), nil
}

// Create takes the representation of a spiderCoordinator and creates it.  Returns the server's representation of the spiderCoordinator, and an error, if there is any.
func (c *FakeSpiderCoordinators) Create(ctx context.Context, spiderCoordinator *v2beta1.SpiderCoordinator, opts v1.CreateOptions) (result *v2beta1.SpiderCoordinator, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Update takes the representation of a spiderCoordinator and updates it. Returns the server's representation of the spiderCoordinator, and an error, if there is any.
func (c *FakeSpiderCoordinators) Update(ctx context.Context, spiderCoordinator *v2beta1.SpiderCoordinator, opts v1.UpdateOptions) (result *v2beta1.SpiderCoordinator, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSpiderCoordinators) UpdateStatus(ctx context.Context, spiderCoordinator *v2beta1.SpiderCoordinator, opts v1.UpdateOptions) (*v2beta1.SpiderCoordinator, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Delete takes name of the spiderCoordinator and deletes it. Returns an error if one occurs.
func (c *FakeSpiderCoordinators) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSpiderCoordinators) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// Patch applies the patch and returns the patched spiderCoordinator.
func (c *FakeSpiderCoordinators) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2beta1.SpiderCoordinator, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}
