// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package runtime

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetRuntimeStartupHandlerFunc turns a function with the right signature into a get runtime startup handler
type GetRuntimeStartupHandlerFunc func(GetRuntimeStartupParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRuntimeStartupHandlerFunc) Handle(params GetRuntimeStartupParams) middleware.Responder {
	_ = "STUB: not implemented"

	// GetRuntimeStartupHandler interface for that can handle valid get runtime startup params
	return *new(middleware.Responder)
}

type GetRuntimeStartupHandler interface {
	Handle(GetRuntimeStartupParams) middleware.Responder
}

// NewGetRuntimeStartup creates a new http.Handler for the get runtime startup operation
func NewGetRuntimeStartup(ctx *middleware.Context, handler GetRuntimeStartupHandler) *GetRuntimeStartup {
	_ = "STUB: not implemented"
	return nil
}

/*
	GetRuntimeStartup swagger:route GET /runtime/startup runtime getRuntimeStartup

# Startup probe

Check pod startup probe
*/
type GetRuntimeStartup struct {
	Context *middleware.Context
	Handler GetRuntimeStartupHandler
}

func (o *GetRuntimeStartup) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// bind params

// actually handle the request
