// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package runtime

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetRuntimeLivenessOKCode is the HTTP code returned for type GetRuntimeLivenessOK
const GetRuntimeLivenessOKCode int = 200

/*
GetRuntimeLivenessOK Success

swagger:response getRuntimeLivenessOK
*/
type GetRuntimeLivenessOK struct {
}

// NewGetRuntimeLivenessOK creates GetRuntimeLivenessOK with default headers values
func NewGetRuntimeLivenessOK() *GetRuntimeLivenessOK { _ = "STUB: not implemented"; return nil }

// WriteResponse to the client
func (o *GetRuntimeLivenessOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

//Remove Content-Type on empty responses

// GetRuntimeLivenessInternalServerErrorCode is the HTTP code returned for type GetRuntimeLivenessInternalServerError
const GetRuntimeLivenessInternalServerErrorCode int = 500

/*
GetRuntimeLivenessInternalServerError Failed

swagger:response getRuntimeLivenessInternalServerError
*/
type GetRuntimeLivenessInternalServerError struct {
}

// NewGetRuntimeLivenessInternalServerError creates GetRuntimeLivenessInternalServerError with default headers values
func NewGetRuntimeLivenessInternalServerError() *GetRuntimeLivenessInternalServerError {
	_ = "STUB: not implemented"
	return nil
}

// WriteResponse to the client
func (o *GetRuntimeLivenessInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

//Remove Content-Type on empty responses
