// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new controller API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	_ = "STUB: not implemented"
	return *new(ClientService)
}

/*
Client for controller API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetIpamStatus(params *GetIpamStatusParams, opts ...ClientOption) (*GetIpamStatusOK, error)

	PostIpamGcIps(params *PostIpamGcIpsParams, opts ...ClientOption) (*PostIpamGcIpsOK, error)

	PutIpamIP(params *PutIpamIPParams, opts ...ClientOption) (*PutIpamIPOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetIpamStatus gets status

Get ipam status for spiderpool controller cli debug usage
*/
func (a *Client) GetIpamStatus(params *GetIpamStatusParams, opts ...ClientOption) (*GetIpamStatusOK, error) {
	_ = "STUB: not implemented"
	// TODO: Validate the params before sending
	return nil, nil
}

// unexpected success response
// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue

/*
PostIpamGcIps triggers gc

Trigger global gc or specific ip gc with the param
*/
func (a *Client) PostIpamGcIps(params *PostIpamGcIpsParams, opts ...ClientOption) (*PostIpamGcIpsOK, error) {
	_ = "STUB: not implemented"
	// TODO: Validate the params before sending
	return nil, nil
}

// unexpected success response
// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue

/*
PutIpamIP forces set ip

Force set ip for spiderpool controller cli debug usage
*/
func (a *Client) PutIpamIP(params *PutIpamIPParams, opts ...ClientOption) (*PutIpamIPOK, error) {
	_ = "STUB: not implemented"
	// TODO: Validate the params before sending
	return nil, nil
}

// unexpected success response
// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) { _ = "STUB: not implemented"; return }
