// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetIpamStatusReader is a Reader for the GetIpamStatus structure.
type GetIpamStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetIpamStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewGetIpamStatusOK creates a GetIpamStatusOK with default headers values
func NewGetIpamStatusOK() *GetIpamStatusOK { _ = "STUB: not implemented"; return nil }

/*
GetIpamStatusOK describes a response with status code 200, with default header values.

Success
*/
type GetIpamStatusOK struct {
}

// IsSuccess returns true when this get ipam status o k response has a 2xx status code
func (o *GetIpamStatusOK) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this get ipam status o k response has a 3xx status code
	return false
}

func (o *GetIpamStatusOK) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this get ipam status o k response has a 4xx status code
	return false
}

func (o *GetIpamStatusOK) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this get ipam status o k response has a 5xx status code
	return false
}

func (o *GetIpamStatusOK) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this get ipam status o k response a status code equal to that given
	return false
}

func (o *GetIpamStatusOK) IsCode(code int) bool {
	_ = "STUB: not implemented"

	// Code gets the status code for the get ipam status o k response
	return false
}

func (o *GetIpamStatusOK) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *GetIpamStatusOK) Error() string { _ = "STUB: not implemented"; return "" }

func (o *GetIpamStatusOK) String() string { _ = "STUB: not implemented"; return "" }

func (o *GetIpamStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// NewGetIpamStatusInternalServerError creates a GetIpamStatusInternalServerError with default headers values
	return nil
}

func NewGetIpamStatusInternalServerError() *GetIpamStatusInternalServerError {
	_ = "STUB: not implemented"
	return nil
}

/*
GetIpamStatusInternalServerError describes a response with status code 500, with default header values.

Get ipam status failure
*/
type GetIpamStatusInternalServerError struct {
}

// IsSuccess returns true when this get ipam status internal server error response has a 2xx status code
func (o *GetIpamStatusInternalServerError) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this get ipam status internal server error response has a 3xx status code
	return false
}

func (o *GetIpamStatusInternalServerError) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this get ipam status internal server error response has a 4xx status code
	return false
}

func (o *GetIpamStatusInternalServerError) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this get ipam status internal server error response has a 5xx status code
	return false
}

func (o *GetIpamStatusInternalServerError) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this get ipam status internal server error response a status code equal to that given
	return false
}

func (o *GetIpamStatusInternalServerError) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the get ipam status internal server error response
}

func (o *GetIpamStatusInternalServerError) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *GetIpamStatusInternalServerError) Error() string { _ = "STUB: not implemented"; return "" }

func (o *GetIpamStatusInternalServerError) String() string { _ = "STUB: not implemented"; return "" }

func (o *GetIpamStatusInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
