// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// NewGetIpamStatusParams creates a new GetIpamStatusParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetIpamStatusParams() *GetIpamStatusParams { _ = "STUB: not implemented"; return nil }

// NewGetIpamStatusParamsWithTimeout creates a new GetIpamStatusParams object
// with the ability to set a timeout on a request.
func NewGetIpamStatusParamsWithTimeout(timeout time.Duration) *GetIpamStatusParams {
	_ = "STUB: not implemented"
	return nil
}

// NewGetIpamStatusParamsWithContext creates a new GetIpamStatusParams object
// with the ability to set a context for a request.
func NewGetIpamStatusParamsWithContext(ctx context.Context) *GetIpamStatusParams {
	_ = "STUB: not implemented"
	return nil
}

// NewGetIpamStatusParamsWithHTTPClient creates a new GetIpamStatusParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetIpamStatusParamsWithHTTPClient(client *http.Client) *GetIpamStatusParams {
	_ = "STUB: not implemented"
	return nil
}

/*
GetIpamStatusParams contains all the parameters to send to the API endpoint

	for the get ipam status operation.

	Typically these are written to a http.Request.
*/
type GetIpamStatusParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get ipam status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetIpamStatusParams) WithDefaults() *GetIpamStatusParams {
	_ = "STUB: not implemented"
	return nil

	// SetDefaults hydrates default values in the get ipam status params (not the query body).
	//
	// All values with no default are reset to their zero value.
}

func (o *GetIpamStatusParams) SetDefaults() {
	_ = "STUB: not implemented"
	// no default values defined for this parameter
	return
}

// WithTimeout adds the timeout to the get ipam status params
func (o *GetIpamStatusParams) WithTimeout(timeout time.Duration) *GetIpamStatusParams {
	_ = "STUB: not implemented"
	return nil
}

// SetTimeout adds the timeout to the get ipam status params
func (o *GetIpamStatusParams) SetTimeout(timeout time.Duration) { _ = "STUB: not implemented"; return }

// WithContext adds the context to the get ipam status params
func (o *GetIpamStatusParams) WithContext(ctx context.Context) *GetIpamStatusParams {
	_ = "STUB: not implemented"
	return nil
}

// SetContext adds the context to the get ipam status params
func (o *GetIpamStatusParams) SetContext(ctx context.Context) {
	_ = "STUB: not implemented"

	// WithHTTPClient adds the HTTPClient to the get ipam status params
	return
}

func (o *GetIpamStatusParams) WithHTTPClient(client *http.Client) *GetIpamStatusParams {
	_ = "STUB: not implemented"
	return nil
}

// SetHTTPClient adds the HTTPClient to the get ipam status params
func (o *GetIpamStatusParams) SetHTTPClient(client *http.Client) { _ = "STUB: not implemented"; return }

// WriteToRequest writes these params to a swagger request
func (o *GetIpamStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
