// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostIpamGcIpsReader is a Reader for the PostIpamGcIps structure.
type PostIpamGcIpsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostIpamGcIpsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewPostIpamGcIpsOK creates a PostIpamGcIpsOK with default headers values
func NewPostIpamGcIpsOK() *PostIpamGcIpsOK { _ = "STUB: not implemented"; return nil }

/*
PostIpamGcIpsOK describes a response with status code 200, with default header values.

Success
*/
type PostIpamGcIpsOK struct {
}

// IsSuccess returns true when this post ipam gc ips o k response has a 2xx status code
func (o *PostIpamGcIpsOK) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this post ipam gc ips o k response has a 3xx status code
	return false
}

func (o *PostIpamGcIpsOK) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this post ipam gc ips o k response has a 4xx status code
	return false
}

func (o *PostIpamGcIpsOK) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this post ipam gc ips o k response has a 5xx status code
	return false
}

func (o *PostIpamGcIpsOK) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this post ipam gc ips o k response a status code equal to that given
	return false
}

func (o *PostIpamGcIpsOK) IsCode(code int) bool {
	_ = "STUB: not implemented"

	// Code gets the status code for the post ipam gc ips o k response
	return false
}

func (o *PostIpamGcIpsOK) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *PostIpamGcIpsOK) Error() string { _ = "STUB: not implemented"; return "" }

func (o *PostIpamGcIpsOK) String() string { _ = "STUB: not implemented"; return "" }

func (o *PostIpamGcIpsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// NewPostIpamGcIpsInternalServerError creates a PostIpamGcIpsInternalServerError with default headers values
	return nil
}

func NewPostIpamGcIpsInternalServerError() *PostIpamGcIpsInternalServerError {
	_ = "STUB: not implemented"
	return nil
}

/*
PostIpamGcIpsInternalServerError describes a response with status code 500, with default header values.

Global gc failure
*/
type PostIpamGcIpsInternalServerError struct {
}

// IsSuccess returns true when this post ipam gc ips internal server error response has a 2xx status code
func (o *PostIpamGcIpsInternalServerError) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this post ipam gc ips internal server error response has a 3xx status code
	return false
}

func (o *PostIpamGcIpsInternalServerError) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this post ipam gc ips internal server error response has a 4xx status code
	return false
}

func (o *PostIpamGcIpsInternalServerError) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this post ipam gc ips internal server error response has a 5xx status code
	return false
}

func (o *PostIpamGcIpsInternalServerError) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this post ipam gc ips internal server error response a status code equal to that given
	return false
}

func (o *PostIpamGcIpsInternalServerError) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the post ipam gc ips internal server error response
}

func (o *PostIpamGcIpsInternalServerError) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *PostIpamGcIpsInternalServerError) Error() string { _ = "STUB: not implemented"; return "" }

func (o *PostIpamGcIpsInternalServerError) String() string { _ = "STUB: not implemented"; return "" }

func (o *PostIpamGcIpsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
