// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// NewPutIpamIPParams creates a new PutIpamIPParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutIpamIPParams() *PutIpamIPParams { _ = "STUB: not implemented"; return nil }

// NewPutIpamIPParamsWithTimeout creates a new PutIpamIPParams object
// with the ability to set a timeout on a request.
func NewPutIpamIPParamsWithTimeout(timeout time.Duration) *PutIpamIPParams {
	_ = "STUB: not implemented"
	return nil
}

// NewPutIpamIPParamsWithContext creates a new PutIpamIPParams object
// with the ability to set a context for a request.
func NewPutIpamIPParamsWithContext(ctx context.Context) *PutIpamIPParams {
	_ = "STUB: not implemented"
	return nil
}

// NewPutIpamIPParamsWithHTTPClient creates a new PutIpamIPParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutIpamIPParamsWithHTTPClient(client *http.Client) *PutIpamIPParams {
	_ = "STUB: not implemented"
	return nil
}

/*
PutIpamIPParams contains all the parameters to send to the API endpoint

	for the put ipam IP operation.

	Typically these are written to a http.Request.
*/
type PutIpamIPParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put ipam IP params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutIpamIPParams) WithDefaults() *PutIpamIPParams { _ = "STUB: not implemented"; return nil }

// SetDefaults hydrates default values in the put ipam IP params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutIpamIPParams) SetDefaults() {
	_ = "STUB: not implemented"
	// no default values defined for this parameter
	return
}

// WithTimeout adds the timeout to the put ipam IP params
func (o *PutIpamIPParams) WithTimeout(timeout time.Duration) *PutIpamIPParams {
	_ = "STUB: not implemented"
	return nil
}

// SetTimeout adds the timeout to the put ipam IP params
func (o *PutIpamIPParams) SetTimeout(timeout time.Duration) { _ = "STUB: not implemented"; return }

// WithContext adds the context to the put ipam IP params
func (o *PutIpamIPParams) WithContext(ctx context.Context) *PutIpamIPParams {
	_ = "STUB: not implemented"
	return nil
}

// SetContext adds the context to the put ipam IP params
func (o *PutIpamIPParams) SetContext(ctx context.Context) {
	_ = "STUB: not implemented"

	// WithHTTPClient adds the HTTPClient to the put ipam IP params
	return
}

func (o *PutIpamIPParams) WithHTTPClient(client *http.Client) *PutIpamIPParams {
	_ = "STUB: not implemented"
	return nil
}

// SetHTTPClient adds the HTTPClient to the put ipam IP params
func (o *PutIpamIPParams) SetHTTPClient(client *http.Client) { _ = "STUB: not implemented"; return }

// WriteToRequest writes these params to a swagger request
func (o *PutIpamIPParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
