// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PutIpamIPReader is a Reader for the PutIpamIP structure.
type PutIpamIPReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutIpamIPReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewPutIpamIPOK creates a PutIpamIPOK with default headers values
func NewPutIpamIPOK() *PutIpamIPOK { _ = "STUB: not implemented"; return nil }

/*
PutIpamIPOK describes a response with status code 200, with default header values.

Success
*/
type PutIpamIPOK struct {
}

// IsSuccess returns true when this put ipam Ip o k response has a 2xx status code
func (o *PutIpamIPOK) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this put ipam Ip o k response has a 3xx status code
	return false
}

func (o *PutIpamIPOK) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this put ipam Ip o k response has a 4xx status code
	return false
}

func (o *PutIpamIPOK) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this put ipam Ip o k response has a 5xx status code
	return false
}

func (o *PutIpamIPOK) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this put ipam Ip o k response a status code equal to that given
	return false
}

func (o *PutIpamIPOK) IsCode(code int) bool {
	_ = "STUB: not implemented"

	// Code gets the status code for the put ipam Ip o k response
	return false
}

func (o *PutIpamIPOK) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *PutIpamIPOK) Error() string { _ = "STUB: not implemented"; return "" }

func (o *PutIpamIPOK) String() string { _ = "STUB: not implemented"; return "" }

func (o *PutIpamIPOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// NewPutIpamIPInternalServerError creates a PutIpamIPInternalServerError with default headers values
	return nil
}

func NewPutIpamIPInternalServerError() *PutIpamIPInternalServerError {
	_ = "STUB: not implemented"
	return nil
}

/*
PutIpamIPInternalServerError describes a response with status code 500, with default header values.

Force set ip failure
*/
type PutIpamIPInternalServerError struct {
}

// IsSuccess returns true when this put ipam Ip internal server error response has a 2xx status code
func (o *PutIpamIPInternalServerError) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this put ipam Ip internal server error response has a 3xx status code
	return false
}

func (o *PutIpamIPInternalServerError) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this put ipam Ip internal server error response has a 4xx status code
	return false
}

func (o *PutIpamIPInternalServerError) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this put ipam Ip internal server error response has a 5xx status code
	return false
}

func (o *PutIpamIPInternalServerError) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this put ipam Ip internal server error response a status code equal to that given
	return false
}

func (o *PutIpamIPInternalServerError) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the put ipam Ip internal server error response
}

func (o *PutIpamIPInternalServerError) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *PutIpamIPInternalServerError) Error() string { _ = "STUB: not implemented"; return "" }

func (o *PutIpamIPInternalServerError) String() string { _ = "STUB: not implemented"; return "" }

func (o *PutIpamIPInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
