// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package versioned

import (
	"net/http"

	spiderpoolv2beta1 "github.com/spidernet-io/spiderpool/pkg/k8s/client/clientset/versioned/typed/spiderpool.spidernet.io/v2beta1"
	discovery "k8s.io/client-go/discovery"
	rest "k8s.io/client-go/rest"
)

type Interface interface {
	Discovery() discovery.DiscoveryInterface
	SpiderpoolV2beta1() spiderpoolv2beta1.SpiderpoolV2beta1Interface
}

// Clientset contains the clients for groups.
type Clientset struct {
	*discovery.DiscoveryClient
	spiderpoolV2beta1 *spiderpoolv2beta1.SpiderpoolV2beta1Client
}

// SpiderpoolV2beta1 retrieves the SpiderpoolV2beta1Client
func (c *Clientset) SpiderpoolV2beta1() spiderpoolv2beta1.SpiderpoolV2beta1Interface {
	_ = "STUB: not implemented"
	return *new(spiderpoolv2beta1.SpiderpoolV2beta1Interface)
}

// Discovery retrieves the DiscoveryClient
func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	_ = "STUB: not implemented"
	return *new(discovery.DiscoveryInterface)
}

// NewForConfig creates a new Clientset for the given config.
// If config's RateLimiter is not set and QPS and Burst are acceptable,
// NewForConfig will generate a rate-limiter in configShallowCopy.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*Clientset, error) { _ = "STUB: not implemented"; return nil, nil }

// share the transport between all clients

// NewForConfigAndClient creates a new Clientset for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
// If config's RateLimiter is not set and QPS and Burst are acceptable,
// NewForConfigAndClient will generate a rate-limiter in configShallowCopy.
func NewForConfigAndClient(c *rest.Config, httpClient *http.Client) (*Clientset, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewForConfigOrDie creates a new Clientset for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *Clientset { _ = "STUB: not implemented"; return nil }

// New creates a new Clientset for the given RESTClient.
func New(c rest.Interface) *Clientset { _ = "STUB: not implemented"; return nil }
