// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package runtime

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new runtime API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	_ = "STUB: not implemented"
	return *new(ClientService)
}

/*
Client for runtime API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetRuntimeLiveness(params *GetRuntimeLivenessParams, opts ...ClientOption) (*GetRuntimeLivenessOK, error)

	GetRuntimeReadiness(params *GetRuntimeReadinessParams, opts ...ClientOption) (*GetRuntimeReadinessOK, error)

	GetRuntimeStartup(params *GetRuntimeStartupParams, opts ...ClientOption) (*GetRuntimeStartupOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetRuntimeLiveness livenesses probe

Check pod liveness probe
*/
func (a *Client) GetRuntimeLiveness(params *GetRuntimeLivenessParams, opts ...ClientOption) (*GetRuntimeLivenessOK, error) {
	_ = "STUB: not implemented"
	// TODO: Validate the params before sending
	return nil, nil
}

// unexpected success response
// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue

/*
GetRuntimeReadiness readinesses probe

Check pod readiness probe
*/
func (a *Client) GetRuntimeReadiness(params *GetRuntimeReadinessParams, opts ...ClientOption) (*GetRuntimeReadinessOK, error) {
	_ = "STUB: not implemented"
	// TODO: Validate the params before sending
	return nil, nil
}

// unexpected success response
// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue

/*
GetRuntimeStartup startups probe

Check pod startup probe
*/
func (a *Client) GetRuntimeStartup(params *GetRuntimeStartupParams, opts ...ClientOption) (*GetRuntimeStartupOK, error) {
	_ = "STUB: not implemented"
	// TODO: Validate the params before sending
	return nil, nil
}

// unexpected success response
// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) { _ = "STUB: not implemented"; return }
