// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by MockGen. DO NOT EDIT.
// Source: ./lease_election.go

// Package mock_election is a generated GoMock package.
package mock_election

import (
	context "context"

	gomock "github.com/golang/mock/gomock"
	kubernetes "k8s.io/client-go/kubernetes"
)

// MockSpiderLeaseElector is a mock of SpiderLeaseElector interface.
type MockSpiderLeaseElector struct {
	ctrl     *gomock.Controller
	recorder *MockSpiderLeaseElectorMockRecorder
}

// MockSpiderLeaseElectorMockRecorder is the mock recorder for MockSpiderLeaseElector.
type MockSpiderLeaseElectorMockRecorder struct {
	mock *MockSpiderLeaseElector
}

// NewMockSpiderLeaseElector creates a new mock instance.
func NewMockSpiderLeaseElector(ctrl *gomock.Controller) *MockSpiderLeaseElector {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpiderLeaseElector) EXPECT() *MockSpiderLeaseElectorMockRecorder {
	_ = "STUB: not implemented"

	// GetLeader mocks base method.
	return nil
}

func (m *MockSpiderLeaseElector) GetLeader() string { _ = "STUB: not implemented"; return "" }

// GetLeader indicates an expected call of GetLeader.
func (mr *MockSpiderLeaseElectorMockRecorder) GetLeader() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsElected mocks base method.
func (m *MockSpiderLeaseElector) IsElected() bool { _ = "STUB: not implemented"; return false }

// IsElected indicates an expected call of IsElected.
func (mr *MockSpiderLeaseElectorMockRecorder) IsElected() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Run mocks base method.
func (m *MockSpiderLeaseElector) Run(ctx context.Context, clientSet kubernetes.Interface) error {
	_ = "STUB: not implemented"
	return nil
}

// Run indicates an expected call of Run.
func (mr *MockSpiderLeaseElectorMockRecorder) Run(ctx, clientSet interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
