// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package runtime

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetRuntimeReadinessReader is a Reader for the GetRuntimeReadiness structure.
type GetRuntimeReadinessReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRuntimeReadinessReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewGetRuntimeReadinessOK creates a GetRuntimeReadinessOK with default headers values
func NewGetRuntimeReadinessOK() *GetRuntimeReadinessOK { _ = "STUB: not implemented"; return nil }

/*
GetRuntimeReadinessOK describes a response with status code 200, with default header values.

Success
*/
type GetRuntimeReadinessOK struct {
}

// IsSuccess returns true when this get runtime readiness o k response has a 2xx status code
func (o *GetRuntimeReadinessOK) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this get runtime readiness o k response has a 3xx status code
	return false
}

func (o *GetRuntimeReadinessOK) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this get runtime readiness o k response has a 4xx status code
	return false
}

func (o *GetRuntimeReadinessOK) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this get runtime readiness o k response has a 5xx status code
	return false
}

func (o *GetRuntimeReadinessOK) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this get runtime readiness o k response a status code equal to that given
	return false
}

func (o *GetRuntimeReadinessOK) IsCode(code int) bool {
	_ = "STUB: not implemented"

	// Code gets the status code for the get runtime readiness o k response
	return false
}

func (o *GetRuntimeReadinessOK) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *GetRuntimeReadinessOK) Error() string { _ = "STUB: not implemented"; return "" }

func (o *GetRuntimeReadinessOK) String() string { _ = "STUB: not implemented"; return "" }

func (o *GetRuntimeReadinessOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// NewGetRuntimeReadinessInternalServerError creates a GetRuntimeReadinessInternalServerError with default headers values
	return nil
}

func NewGetRuntimeReadinessInternalServerError() *GetRuntimeReadinessInternalServerError {
	_ = "STUB: not implemented"
	return nil
}

/*
GetRuntimeReadinessInternalServerError describes a response with status code 500, with default header values.

Failed
*/
type GetRuntimeReadinessInternalServerError struct {
}

// IsSuccess returns true when this get runtime readiness internal server error response has a 2xx status code
func (o *GetRuntimeReadinessInternalServerError) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this get runtime readiness internal server error response has a 3xx status code
	return false
}

func (o *GetRuntimeReadinessInternalServerError) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this get runtime readiness internal server error response has a 4xx status code
	return false
}

func (o *GetRuntimeReadinessInternalServerError) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this get runtime readiness internal server error response has a 5xx status code
	return false
}

func (o *GetRuntimeReadinessInternalServerError) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this get runtime readiness internal server error response a status code equal to that given
	return false
}

func (o *GetRuntimeReadinessInternalServerError) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the get runtime readiness internal server error response
}

func (o *GetRuntimeReadinessInternalServerError) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *GetRuntimeReadinessInternalServerError) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *GetRuntimeReadinessInternalServerError) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *GetRuntimeReadinessInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
