// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package runtime

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// NewGetRuntimeLivenessParams creates a new GetRuntimeLivenessParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRuntimeLivenessParams() *GetRuntimeLivenessParams { _ = "STUB: not implemented"; return nil }

// NewGetRuntimeLivenessParamsWithTimeout creates a new GetRuntimeLivenessParams object
// with the ability to set a timeout on a request.
func NewGetRuntimeLivenessParamsWithTimeout(timeout time.Duration) *GetRuntimeLivenessParams {
	_ = "STUB: not implemented"
	return nil
}

// NewGetRuntimeLivenessParamsWithContext creates a new GetRuntimeLivenessParams object
// with the ability to set a context for a request.
func NewGetRuntimeLivenessParamsWithContext(ctx context.Context) *GetRuntimeLivenessParams {
	_ = "STUB: not implemented"
	return nil
}

// NewGetRuntimeLivenessParamsWithHTTPClient creates a new GetRuntimeLivenessParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRuntimeLivenessParamsWithHTTPClient(client *http.Client) *GetRuntimeLivenessParams {
	_ = "STUB: not implemented"
	return nil
}

/*
GetRuntimeLivenessParams contains all the parameters to send to the API endpoint

	for the get runtime liveness operation.

	Typically these are written to a http.Request.
*/
type GetRuntimeLivenessParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get runtime liveness params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRuntimeLivenessParams) WithDefaults() *GetRuntimeLivenessParams {
	_ = "STUB: not implemented"
	return nil

	// SetDefaults hydrates default values in the get runtime liveness params (not the query body).
	//
	// All values with no default are reset to their zero value.
}

func (o *GetRuntimeLivenessParams) SetDefaults() {
	_ = "STUB: not implemented"
	// no default values defined for this parameter
	return
}

// WithTimeout adds the timeout to the get runtime liveness params
func (o *GetRuntimeLivenessParams) WithTimeout(timeout time.Duration) *GetRuntimeLivenessParams {
	_ = "STUB: not implemented"
	return nil
}

// SetTimeout adds the timeout to the get runtime liveness params
func (o *GetRuntimeLivenessParams) SetTimeout(timeout time.Duration) {
	_ = "STUB: not implemented"
	return

	// WithContext adds the context to the get runtime liveness params
}

func (o *GetRuntimeLivenessParams) WithContext(ctx context.Context) *GetRuntimeLivenessParams {
	_ = "STUB: not implemented"
	return nil
}

// SetContext adds the context to the get runtime liveness params
func (o *GetRuntimeLivenessParams) SetContext(ctx context.Context) {
	_ = "STUB: not implemented"

	// WithHTTPClient adds the HTTPClient to the get runtime liveness params
	return
}

func (o *GetRuntimeLivenessParams) WithHTTPClient(client *http.Client) *GetRuntimeLivenessParams {
	_ = "STUB: not implemented"
	return nil
}

// SetHTTPClient adds the HTTPClient to the get runtime liveness params
func (o *GetRuntimeLivenessParams) SetHTTPClient(client *http.Client) {
	_ = "STUB: not implemented"
	return

	// WriteToRequest writes these params to a swagger request
}

func (o *GetRuntimeLivenessParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
