// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package runtime

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetRuntimeLivenessReader is a Reader for the GetRuntimeLiveness structure.
type GetRuntimeLivenessReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRuntimeLivenessReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewGetRuntimeLivenessOK creates a GetRuntimeLivenessOK with default headers values
func NewGetRuntimeLivenessOK() *GetRuntimeLivenessOK { _ = "STUB: not implemented"; return nil }

/*
GetRuntimeLivenessOK describes a response with status code 200, with default header values.

Success
*/
type GetRuntimeLivenessOK struct {
}

// IsSuccess returns true when this get runtime liveness o k response has a 2xx status code
func (o *GetRuntimeLivenessOK) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this get runtime liveness o k response has a 3xx status code
	return false
}

func (o *GetRuntimeLivenessOK) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this get runtime liveness o k response has a 4xx status code
	return false
}

func (o *GetRuntimeLivenessOK) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this get runtime liveness o k response has a 5xx status code
	return false
}

func (o *GetRuntimeLivenessOK) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this get runtime liveness o k response a status code equal to that given
	return false
}

func (o *GetRuntimeLivenessOK) IsCode(code int) bool {
	_ = "STUB: not implemented"

	// Code gets the status code for the get runtime liveness o k response
	return false
}

func (o *GetRuntimeLivenessOK) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *GetRuntimeLivenessOK) Error() string { _ = "STUB: not implemented"; return "" }

func (o *GetRuntimeLivenessOK) String() string { _ = "STUB: not implemented"; return "" }

func (o *GetRuntimeLivenessOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// NewGetRuntimeLivenessInternalServerError creates a GetRuntimeLivenessInternalServerError with default headers values
	return nil
}

func NewGetRuntimeLivenessInternalServerError() *GetRuntimeLivenessInternalServerError {
	_ = "STUB: not implemented"
	return nil
}

/*
GetRuntimeLivenessInternalServerError describes a response with status code 500, with default header values.

Failed
*/
type GetRuntimeLivenessInternalServerError struct {
}

// IsSuccess returns true when this get runtime liveness internal server error response has a 2xx status code
func (o *GetRuntimeLivenessInternalServerError) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this get runtime liveness internal server error response has a 3xx status code
	return false
}

func (o *GetRuntimeLivenessInternalServerError) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this get runtime liveness internal server error response has a 4xx status code
	return false
}

func (o *GetRuntimeLivenessInternalServerError) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this get runtime liveness internal server error response has a 5xx status code
	return false
}

func (o *GetRuntimeLivenessInternalServerError) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this get runtime liveness internal server error response a status code equal to that given
	return false
}

func (o *GetRuntimeLivenessInternalServerError) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the get runtime liveness internal server error response
}

func (o *GetRuntimeLivenessInternalServerError) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *GetRuntimeLivenessInternalServerError) Error() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *GetRuntimeLivenessInternalServerError) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *GetRuntimeLivenessInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
