// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package runtime

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// NewGetRuntimeReadinessParams creates a new GetRuntimeReadinessParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetRuntimeReadinessParams() *GetRuntimeReadinessParams {
	_ = "STUB: not implemented"
	return nil
}

// NewGetRuntimeReadinessParamsWithTimeout creates a new GetRuntimeReadinessParams object
// with the ability to set a timeout on a request.
func NewGetRuntimeReadinessParamsWithTimeout(timeout time.Duration) *GetRuntimeReadinessParams {
	_ = "STUB: not implemented"
	return nil
}

// NewGetRuntimeReadinessParamsWithContext creates a new GetRuntimeReadinessParams object
// with the ability to set a context for a request.
func NewGetRuntimeReadinessParamsWithContext(ctx context.Context) *GetRuntimeReadinessParams {
	_ = "STUB: not implemented"
	return nil
}

// NewGetRuntimeReadinessParamsWithHTTPClient creates a new GetRuntimeReadinessParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetRuntimeReadinessParamsWithHTTPClient(client *http.Client) *GetRuntimeReadinessParams {
	_ = "STUB: not implemented"
	return nil
}

/*
GetRuntimeReadinessParams contains all the parameters to send to the API endpoint

	for the get runtime readiness operation.

	Typically these are written to a http.Request.
*/
type GetRuntimeReadinessParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get runtime readiness params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetRuntimeReadinessParams) WithDefaults() *GetRuntimeReadinessParams {
	_ = "STUB: not implemented"
	return nil

	// SetDefaults hydrates default values in the get runtime readiness params (not the query body).
	//
	// All values with no default are reset to their zero value.
}

func (o *GetRuntimeReadinessParams) SetDefaults() {
	_ = "STUB: not implemented"
	// no default values defined for this parameter
	return
}

// WithTimeout adds the timeout to the get runtime readiness params
func (o *GetRuntimeReadinessParams) WithTimeout(timeout time.Duration) *GetRuntimeReadinessParams {
	_ = "STUB: not implemented"
	return nil
}

// SetTimeout adds the timeout to the get runtime readiness params
func (o *GetRuntimeReadinessParams) SetTimeout(timeout time.Duration) {
	_ = "STUB: not implemented"
	return

	// WithContext adds the context to the get runtime readiness params
}

func (o *GetRuntimeReadinessParams) WithContext(ctx context.Context) *GetRuntimeReadinessParams {
	_ = "STUB: not implemented"
	return nil
}

// SetContext adds the context to the get runtime readiness params
func (o *GetRuntimeReadinessParams) SetContext(ctx context.Context) {
	_ = "STUB: not implemented"

	// WithHTTPClient adds the HTTPClient to the get runtime readiness params
	return
}

func (o *GetRuntimeReadinessParams) WithHTTPClient(client *http.Client) *GetRuntimeReadinessParams {
	_ = "STUB: not implemented"
	return nil
}

// SetHTTPClient adds the HTTPClient to the get runtime readiness params
func (o *GetRuntimeReadinessParams) SetHTTPClient(client *http.Client) {
	_ = "STUB: not implemented"
	return

	// WriteToRequest writes these params to a swagger request
}

func (o *GetRuntimeReadinessParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
