// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package runtime

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetRuntimeStartupReader is a Reader for the GetRuntimeStartup structure.
type GetRuntimeStartupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRuntimeStartupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewGetRuntimeStartupOK creates a GetRuntimeStartupOK with default headers values
func NewGetRuntimeStartupOK() *GetRuntimeStartupOK { _ = "STUB: not implemented"; return nil }

/*
GetRuntimeStartupOK describes a response with status code 200, with default header values.

Success
*/
type GetRuntimeStartupOK struct {
}

// IsSuccess returns true when this get runtime startup o k response has a 2xx status code
func (o *GetRuntimeStartupOK) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this get runtime startup o k response has a 3xx status code
	return false
}

func (o *GetRuntimeStartupOK) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this get runtime startup o k response has a 4xx status code
	return false
}

func (o *GetRuntimeStartupOK) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this get runtime startup o k response has a 5xx status code
	return false
}

func (o *GetRuntimeStartupOK) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this get runtime startup o k response a status code equal to that given
	return false
}

func (o *GetRuntimeStartupOK) IsCode(code int) bool {
	_ = "STUB: not implemented"

	// Code gets the status code for the get runtime startup o k response
	return false
}

func (o *GetRuntimeStartupOK) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *GetRuntimeStartupOK) Error() string { _ = "STUB: not implemented"; return "" }

func (o *GetRuntimeStartupOK) String() string { _ = "STUB: not implemented"; return "" }

func (o *GetRuntimeStartupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// NewGetRuntimeStartupInternalServerError creates a GetRuntimeStartupInternalServerError with default headers values
	return nil
}

func NewGetRuntimeStartupInternalServerError() *GetRuntimeStartupInternalServerError {
	_ = "STUB: not implemented"
	return nil
}

/*
GetRuntimeStartupInternalServerError describes a response with status code 500, with default header values.

Failed
*/
type GetRuntimeStartupInternalServerError struct {
}

// IsSuccess returns true when this get runtime startup internal server error response has a 2xx status code
func (o *GetRuntimeStartupInternalServerError) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this get runtime startup internal server error response has a 3xx status code
	return false
}

func (o *GetRuntimeStartupInternalServerError) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this get runtime startup internal server error response has a 4xx status code
	return false
}

func (o *GetRuntimeStartupInternalServerError) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this get runtime startup internal server error response has a 5xx status code
	return false
}

func (o *GetRuntimeStartupInternalServerError) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this get runtime startup internal server error response a status code equal to that given
	return false
}

func (o *GetRuntimeStartupInternalServerError) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the get runtime startup internal server error response
}

func (o *GetRuntimeStartupInternalServerError) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *GetRuntimeStartupInternalServerError) Error() string { _ = "STUB: not implemented"; return "" }

func (o *GetRuntimeStartupInternalServerError) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (o *GetRuntimeStartupInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
