// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package connectivity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetIpamHealthyReader is a Reader for the GetIpamHealthy structure.
type GetIpamHealthyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetIpamHealthyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewGetIpamHealthyOK creates a GetIpamHealthyOK with default headers values
func NewGetIpamHealthyOK() *GetIpamHealthyOK { _ = "STUB: not implemented"; return nil }

/*
GetIpamHealthyOK describes a response with status code 200, with default header values.

Success
*/
type GetIpamHealthyOK struct {
}

// IsSuccess returns true when this get ipam healthy o k response has a 2xx status code
func (o *GetIpamHealthyOK) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this get ipam healthy o k response has a 3xx status code
	return false
}

func (o *GetIpamHealthyOK) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this get ipam healthy o k response has a 4xx status code
	return false
}

func (o *GetIpamHealthyOK) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this get ipam healthy o k response has a 5xx status code
	return false
}

func (o *GetIpamHealthyOK) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this get ipam healthy o k response a status code equal to that given
	return false
}

func (o *GetIpamHealthyOK) IsCode(code int) bool {
	_ = "STUB: not implemented"

	// Code gets the status code for the get ipam healthy o k response
	return false
}

func (o *GetIpamHealthyOK) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *GetIpamHealthyOK) Error() string { _ = "STUB: not implemented"; return "" }

func (o *GetIpamHealthyOK) String() string { _ = "STUB: not implemented"; return "" }

func (o *GetIpamHealthyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// NewGetIpamHealthyInternalServerError creates a GetIpamHealthyInternalServerError with default headers values
	return nil
}

func NewGetIpamHealthyInternalServerError() *GetIpamHealthyInternalServerError {
	_ = "STUB: not implemented"
	return nil
}

/*
GetIpamHealthyInternalServerError describes a response with status code 500, with default header values.

Failed
*/
type GetIpamHealthyInternalServerError struct {
}

// IsSuccess returns true when this get ipam healthy internal server error response has a 2xx status code
func (o *GetIpamHealthyInternalServerError) IsSuccess() bool {
	_ = "STUB: not implemented"

	// IsRedirect returns true when this get ipam healthy internal server error response has a 3xx status code
	return false
}

func (o *GetIpamHealthyInternalServerError) IsRedirect() bool {
	_ = "STUB: not implemented"

	// IsClientError returns true when this get ipam healthy internal server error response has a 4xx status code
	return false
}

func (o *GetIpamHealthyInternalServerError) IsClientError() bool {
	_ = "STUB: not implemented"

	// IsServerError returns true when this get ipam healthy internal server error response has a 5xx status code
	return false
}

func (o *GetIpamHealthyInternalServerError) IsServerError() bool {
	_ = "STUB: not implemented"

	// IsCode returns true when this get ipam healthy internal server error response a status code equal to that given
	return false
}

func (o *GetIpamHealthyInternalServerError) IsCode(code int) bool {
	_ = "STUB: not implemented"
	return false

	// Code gets the status code for the get ipam healthy internal server error response
}

func (o *GetIpamHealthyInternalServerError) Code() int { _ = "STUB: not implemented"; return 0 }

func (o *GetIpamHealthyInternalServerError) Error() string { _ = "STUB: not implemented"; return "" }

func (o *GetIpamHealthyInternalServerError) String() string { _ = "STUB: not implemented"; return "" }

func (o *GetIpamHealthyInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
