// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package connectivity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// NewGetIpamHealthyParams creates a new GetIpamHealthyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetIpamHealthyParams() *GetIpamHealthyParams { _ = "STUB: not implemented"; return nil }

// NewGetIpamHealthyParamsWithTimeout creates a new GetIpamHealthyParams object
// with the ability to set a timeout on a request.
func NewGetIpamHealthyParamsWithTimeout(timeout time.Duration) *GetIpamHealthyParams {
	_ = "STUB: not implemented"
	return nil
}

// NewGetIpamHealthyParamsWithContext creates a new GetIpamHealthyParams object
// with the ability to set a context for a request.
func NewGetIpamHealthyParamsWithContext(ctx context.Context) *GetIpamHealthyParams {
	_ = "STUB: not implemented"
	return nil
}

// NewGetIpamHealthyParamsWithHTTPClient creates a new GetIpamHealthyParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetIpamHealthyParamsWithHTTPClient(client *http.Client) *GetIpamHealthyParams {
	_ = "STUB: not implemented"
	return nil
}

/*
GetIpamHealthyParams contains all the parameters to send to the API endpoint

	for the get ipam healthy operation.

	Typically these are written to a http.Request.
*/
type GetIpamHealthyParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get ipam healthy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetIpamHealthyParams) WithDefaults() *GetIpamHealthyParams {
	_ = "STUB: not implemented"
	return nil

	// SetDefaults hydrates default values in the get ipam healthy params (not the query body).
	//
	// All values with no default are reset to their zero value.
}

func (o *GetIpamHealthyParams) SetDefaults() {
	_ = "STUB: not implemented"
	// no default values defined for this parameter
	return
}

// WithTimeout adds the timeout to the get ipam healthy params
func (o *GetIpamHealthyParams) WithTimeout(timeout time.Duration) *GetIpamHealthyParams {
	_ = "STUB: not implemented"
	return nil
}

// SetTimeout adds the timeout to the get ipam healthy params
func (o *GetIpamHealthyParams) SetTimeout(timeout time.Duration) { _ = "STUB: not implemented"; return }

// WithContext adds the context to the get ipam healthy params
func (o *GetIpamHealthyParams) WithContext(ctx context.Context) *GetIpamHealthyParams {
	_ = "STUB: not implemented"
	return nil
}

// SetContext adds the context to the get ipam healthy params
func (o *GetIpamHealthyParams) SetContext(ctx context.Context) {
	_ = "STUB: not implemented"

	// WithHTTPClient adds the HTTPClient to the get ipam healthy params
	return
}

func (o *GetIpamHealthyParams) WithHTTPClient(client *http.Client) *GetIpamHealthyParams {
	_ = "STUB: not implemented"
	return nil
}

// SetHTTPClient adds the HTTPClient to the get ipam healthy params
func (o *GetIpamHealthyParams) SetHTTPClient(client *http.Client) {
	_ = "STUB: not implemented"
	return

	// WriteToRequest writes these params to a swagger request
}

func (o *GetIpamHealthyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}
