// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package server

import (
	"net"
	"net/http"
	"os"
	"sync"
	"time"

	"github.com/go-openapi/runtime/flagext"
	flags "github.com/jessevdk/go-flags"

	"github.com/spidernet-io/spiderpool/api/v1/agent/server/restapi"
)

const (
	schemeHTTP  = "http"
	schemeHTTPS = "https"
	schemeUnix  = "unix"
)

var defaultSchemes []string

func init() {
	defaultSchemes = []string{
		schemeUnix,
	}
}

// NewServer creates a new api spiderpool agent API server but does not configure it
func NewServer(api *restapi.SpiderpoolAgentAPIAPI) *Server { _ = "STUB: not implemented"; return nil }

// ConfigureAPI configures the API and handlers.
func (s *Server) ConfigureAPI() { _ = "STUB: not implemented"; return }

// ConfigureFlags configures the additional flags defined by the handlers. Needs to be called before the parser.Parse
func (s *Server) ConfigureFlags() { _ = "STUB: not implemented"; return }

// Server for the spiderpool agent API API
type Server struct {
	EnabledListeners []string         `long:"scheme" description:"the listeners to enable, this can be repeated and defaults to the schemes in the swagger spec"`
	CleanupTimeout   time.Duration    `long:"cleanup-timeout" description:"grace period for which to wait before killing idle connections" default:"10s"`
	GracefulTimeout  time.Duration    `long:"graceful-timeout" description:"grace period for which to wait before shutting down the server" default:"15s"`
	MaxHeaderSize    flagext.ByteSize `long:"max-header-size" description:"controls the maximum number of bytes the server will read parsing the request header's keys and values, including the request line. It does not limit the size of the request body." default:"1MiB"`

	SocketPath    flags.Filename `long:"socket-path" description:"the unix socket to listen on" default:"/var/run/spiderpool-agent-api.sock"`
	domainSocketL net.Listener

	Host         string        `long:"host" description:"the IP to listen on" default:"localhost" env:"HOST"`
	Port         int           `long:"port" description:"the port to listen on for insecure connections, defaults to a random value" env:"PORT"`
	ListenLimit  int           `long:"listen-limit" description:"limit the number of outstanding requests"`
	KeepAlive    time.Duration `long:"keep-alive" description:"sets the TCP keep-alive timeouts on accepted connections. It prunes dead TCP connections ( e.g. closing laptop mid-download)" default:"3m"`
	ReadTimeout  time.Duration `long:"read-timeout" description:"maximum duration before timing out read of the request" default:"30s"`
	WriteTimeout time.Duration `long:"write-timeout" description:"maximum duration before timing out write of the response" default:"60s"`
	httpServerL  net.Listener

	TLSHost           string         `long:"tls-host" description:"the IP to listen on for tls, when not specified it's the same as --host" env:"TLS_HOST"`
	TLSPort           int            `long:"tls-port" description:"the port to listen on for secure connections, defaults to a random value" env:"TLS_PORT"`
	TLSCertificate    flags.Filename `long:"tls-certificate" description:"the certificate to use for secure connections" env:"TLS_CERTIFICATE"`
	TLSCertificateKey flags.Filename `long:"tls-key" description:"the private key to use for secure connections" env:"TLS_PRIVATE_KEY"`
	TLSCACertificate  flags.Filename `long:"tls-ca" description:"the certificate authority file to be used with mutual tls auth" env:"TLS_CA_CERTIFICATE"`
	TLSListenLimit    int            `long:"tls-listen-limit" description:"limit the number of outstanding requests"`
	TLSKeepAlive      time.Duration  `long:"tls-keep-alive" description:"sets the TCP keep-alive timeouts on accepted connections. It prunes dead TCP connections ( e.g. closing laptop mid-download)"`
	TLSReadTimeout    time.Duration  `long:"tls-read-timeout" description:"maximum duration before timing out read of the request"`
	TLSWriteTimeout   time.Duration  `long:"tls-write-timeout" description:"maximum duration before timing out write of the response"`
	httpsServerL      net.Listener

	api          *restapi.SpiderpoolAgentAPIAPI
	handler      http.Handler
	hasListeners bool
	shutdown     chan struct{}
	shuttingDown int32
	interrupted  bool
	interrupt    chan os.Signal
}

// Logf logs message either via defined user logger or via system one if no user logger is defined.
func (s *Server) Logf(f string, args ...interface{}) { _ = "STUB: not implemented"; return }

// Fatalf logs message either via defined user logger or via system one if no user logger is defined.
// Exits with non-zero status after printing
func (s *Server) Fatalf(f string, args ...interface{}) { _ = "STUB: not implemented"; return }

// SetAPI configures the server with the specified API. Needs to be called before Serve
func (s *Server) SetAPI(api *restapi.SpiderpoolAgentAPIAPI) { _ = "STUB: not implemented"; return }

func (s *Server) hasScheme(scheme string) bool { _ = "STUB: not implemented"; return false }

// Serve the api
func (s *Server) Serve() (err error) { _ = "STUB: not implemented"; return nil }

// set default handler, if none is set

// Inspired by https://blog.bracebin.com/achieving-perfect-ssl-labs-score-with-go

// Causes servers to use Go's default ciphersuite preferences,
// which are tuned to avoid attacks. Does nothing on clients.

// Only use curves which have assembly implementations
// https://github.com/golang/go/tree/master/src/crypto/elliptic

// Use modern tls mode https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility

// https://www.owasp.org/index.php/Transport_Layer_Protection_Cheat_Sheet#Rule_-_Only_Support_Strong_Protocols

// These ciphersuites support Forward Secrecy: https://en.wikipedia.org/wiki/Forward_secrecy

// build standard config from server options

// include specified CA certificate

// call custom TLS configurator

// after standard and custom config are passed, this ends up with no certificate

// this happens with a wrong custom TLS configurator

// Listen creates the listeners for the server
func (s *Server) Listen() error {
	_ = "STUB: not implemented"
	// already done this
	return nil
}

// Use http host if https host wasn't defined

// Use http listen limit if https listen limit wasn't defined

// Use http tcp keep alive if https tcp keep alive wasn't defined

// Use http read timeout if https read timeout wasn't defined

// Use http write timeout if https write timeout wasn't defined

// Shutdown server and clean up resources
func (s *Server) Shutdown() error { _ = "STUB: not implemented"; return nil }

func (s *Server) handleShutdown(wg *sync.WaitGroup, serversPtr *[]*http.Server) {
	_ = "STUB: not implemented"
	// wg.Done must occur last, after s.api.ServerShutdown()
	// (to preserve old behaviour)
	return
}

// first execute the pre-shutdown hook

// Error from closing listeners, or context timeout:

// Wait until all listeners have successfully shut down before calling ServerShutdown

// GetHandler returns a handler useful for testing
func (s *Server) GetHandler() http.Handler {
	_ = "STUB: not implemented"

	// SetHandler allows for setting a http handler on this server
	return *new(http.Handler)
}

func (s *Server) SetHandler(handler http.Handler) { _ = "STUB: not implemented"; return }

// UnixListener returns the domain socket listener
func (s *Server) UnixListener() (net.Listener, error) {
	_ = "STUB: not implemented"
	return *new(net.Listener), nil
}

// HTTPListener returns the http listener
func (s *Server) HTTPListener() (net.Listener, error) {
	_ = "STUB: not implemented"
	return *new(net.Listener), nil
}

// TLSListener returns the https listener
func (s *Server) TLSListener() (net.Listener, error) {
	_ = "STUB: not implemented"
	return *new(net.Listener), nil
}

func handleInterrupt(once *sync.Once, s *Server) { _ = "STUB: not implemented"; return }

func signalNotify(interrupt chan<- os.Signal) { _ = "STUB: not implemented"; return }
