// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v2beta1

import (
	v2beta1 "github.com/spidernet-io/spiderpool/pkg/k8s/apis/spiderpool.spidernet.io/v2beta1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// SpiderCoordinatorLister helps list SpiderCoordinators.
// All objects returned here must be treated as read-only.
type SpiderCoordinatorLister interface {
	// List lists all SpiderCoordinators in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v2beta1.SpiderCoordinator, err error)
	// Get retrieves the SpiderCoordinator from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v2beta1.SpiderCoordinator, error)
	SpiderCoordinatorListerExpansion
}

// spiderCoordinatorLister implements the SpiderCoordinatorLister interface.
type spiderCoordinatorLister struct {
	indexer cache.Indexer
}

// NewSpiderCoordinatorLister returns a new SpiderCoordinatorLister.
func NewSpiderCoordinatorLister(indexer cache.Indexer) SpiderCoordinatorLister {
	_ = "STUB: not implemented"
	return *new(SpiderCoordinatorLister)
}

// List lists all SpiderCoordinators in the indexer.
func (s *spiderCoordinatorLister) List(selector labels.Selector) (ret []*v2beta1.SpiderCoordinator, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Get retrieves the SpiderCoordinator from the index for a given name.
func (s *spiderCoordinatorLister) Get(name string) (*v2beta1.SpiderCoordinator, error) {
	_ = "STUB: not implemented"
	return nil, nil
}
