// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v2beta1

import (
	v2beta1 "github.com/spidernet-io/spiderpool/pkg/k8s/apis/spiderpool.spidernet.io/v2beta1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// SpiderSubnetLister helps list SpiderSubnets.
// All objects returned here must be treated as read-only.
type SpiderSubnetLister interface {
	// List lists all SpiderSubnets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v2beta1.SpiderSubnet, err error)
	// Get retrieves the SpiderSubnet from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v2beta1.SpiderSubnet, error)
	SpiderSubnetListerExpansion
}

// spiderSubnetLister implements the SpiderSubnetLister interface.
type spiderSubnetLister struct {
	indexer cache.Indexer
}

// NewSpiderSubnetLister returns a new SpiderSubnetLister.
func NewSpiderSubnetLister(indexer cache.Indexer) SpiderSubnetLister {
	_ = "STUB: not implemented"
	return *new(SpiderSubnetLister)
}

// List lists all SpiderSubnets in the indexer.
func (s *spiderSubnetLister) List(selector labels.Selector) (ret []*v2beta1.SpiderSubnet, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Get retrieves the SpiderSubnet from the index for a given name.
func (s *spiderSubnetLister) Get(name string) (*v2beta1.SpiderSubnet, error) {
	_ = "STUB: not implemented"
	return nil, nil
}
