// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package daemonset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteIpamIpsHandlerFunc turns a function with the right signature into a delete ipam ips handler
type DeleteIpamIpsHandlerFunc func(DeleteIpamIpsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteIpamIpsHandlerFunc) Handle(params DeleteIpamIpsParams) middleware.Responder {
	_ = "STUB: not implemented"

	// DeleteIpamIpsHandler interface for that can handle valid delete ipam ips params
	return *new(middleware.Responder)
}

type DeleteIpamIpsHandler interface {
	Handle(DeleteIpamIpsParams) middleware.Responder
}

// NewDeleteIpamIps creates a new http.Handler for the delete ipam ips operation
func NewDeleteIpamIps(ctx *middleware.Context, handler DeleteIpamIpsHandler) *DeleteIpamIps {
	_ = "STUB: not implemented"
	return nil
}

/*
	DeleteIpamIps swagger:route DELETE /ipam/ips daemonset deleteIpamIps

# Delete multiple ip as a batch

Delete multiple ip for a pod, case for spiderflat compent
*/
type DeleteIpamIps struct {
	Context *middleware.Context
	Handler DeleteIpamIpsHandler
}

func (o *DeleteIpamIps) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// bind params

// actually handle the request
