// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package daemonset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteIpamIPHandlerFunc turns a function with the right signature into a delete ipam IP handler
type DeleteIpamIPHandlerFunc func(DeleteIpamIPParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteIpamIPHandlerFunc) Handle(params DeleteIpamIPParams) middleware.Responder {
	_ = "STUB: not implemented"

	// DeleteIpamIPHandler interface for that can handle valid delete ipam IP params
	return *new(middleware.Responder)
}

type DeleteIpamIPHandler interface {
	Handle(DeleteIpamIPParams) middleware.Responder
}

// NewDeleteIpamIP creates a new http.Handler for the delete ipam IP operation
func NewDeleteIpamIP(ctx *middleware.Context, handler DeleteIpamIPHandler) *DeleteIpamIP {
	_ = "STUB: not implemented"
	return nil
}

/*
	DeleteIpamIP swagger:route DELETE /ipam/ip daemonset deleteIpamIp

# Delete ip from spiderpool daemon

Send a request to daemonset to ask for an ip deleting
*/
type DeleteIpamIP struct {
	Context *middleware.Context
	Handler DeleteIpamIPHandler
}

func (o *DeleteIpamIP) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// bind params

// actually handle the request
