// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package daemonset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/spidernet-io/spiderpool/api/v1/agent/models"
)

// NewDeleteIpamIpsParams creates a new DeleteIpamIpsParams object
//
// There are no default values defined in the spec.
func NewDeleteIpamIpsParams() DeleteIpamIpsParams {
	_ = "STUB: not implemented"
	return *new(DeleteIpamIpsParams)
}

// DeleteIpamIpsParams contains all the bound params for the delete ipam ips operation
// typically these are obtained from a http.Request
//
// swagger:parameters DeleteIpamIps
type DeleteIpamIpsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	IpamBatchDelArgs *models.IpamBatchDelArgs
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteIpamIpsParams() beforehand.
func (o *DeleteIpamIpsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	_ = "STUB: not implemented"
	return nil
}

// validate body object
