// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package daemonset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetWorkloadendpointParams creates a new GetWorkloadendpointParams object
//
// There are no default values defined in the spec.
func NewGetWorkloadendpointParams() GetWorkloadendpointParams {
	_ = "STUB: not implemented"
	return *new(GetWorkloadendpointParams)
}

// GetWorkloadendpointParams contains all the bound params for the get workloadendpoint operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetWorkloadendpoint
type GetWorkloadendpointParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Pod name
	  Required: true
	  In: query
	*/
	PodName string
	/*Pod namespace
	  Required: true
	  In: query
	*/
	PodNamespace string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetWorkloadendpointParams() beforehand.
func (o *GetWorkloadendpointParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	_ = "STUB: not implemented"
	return nil
}

// bindPodName binds and validates parameter PodName from query.
func (o *GetWorkloadendpointParams) bindPodName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: true
// AllowEmptyValue: false

// bindPodNamespace binds and validates parameter PodNamespace from query.
func (o *GetWorkloadendpointParams) bindPodNamespace(rawData []string, hasKey bool, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// Required: true
// AllowEmptyValue: false
