// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package daemonset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/spidernet-io/spiderpool/api/v1/agent/models"
)

// GetWorkloadendpointOKCode is the HTTP code returned for type GetWorkloadendpointOK
const GetWorkloadendpointOKCode int = 200

/*
GetWorkloadendpointOK Success

swagger:response getWorkloadendpointOK
*/
type GetWorkloadendpointOK struct {

	/*
	  In: Body
	*/
	Payload *models.WorkloadEndpointStatus `json:"body,omitempty"`
}

// NewGetWorkloadendpointOK creates GetWorkloadendpointOK with default headers values
func NewGetWorkloadendpointOK() *GetWorkloadendpointOK { _ = "STUB: not implemented"; return nil }

// WithPayload adds the payload to the get workloadendpoint o k response
func (o *GetWorkloadendpointOK) WithPayload(payload *models.WorkloadEndpointStatus) *GetWorkloadendpointOK {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the get workloadendpoint o k response
func (o *GetWorkloadendpointOK) SetPayload(payload *models.WorkloadEndpointStatus) {
	_ = "STUB: not implemented"
	return

	// WriteResponse to the client
}

func (o *GetWorkloadendpointOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this

// GetWorkloadendpointBadRequestCode is the HTTP code returned for type GetWorkloadendpointBadRequest
const GetWorkloadendpointBadRequestCode int = 400

/*
GetWorkloadendpointBadRequest Missing or invalid parameters

swagger:response getWorkloadendpointBadRequest
*/
type GetWorkloadendpointBadRequest struct {

	/*
	  In: Body
	*/
	Payload models.Error `json:"body,omitempty"`
}

// NewGetWorkloadendpointBadRequest creates GetWorkloadendpointBadRequest with default headers values
func NewGetWorkloadendpointBadRequest() *GetWorkloadendpointBadRequest {
	_ = "STUB: not implemented"
	return nil
}

// WithPayload adds the payload to the get workloadendpoint bad request response
func (o *GetWorkloadendpointBadRequest) WithPayload(payload models.Error) *GetWorkloadendpointBadRequest {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the get workloadendpoint bad request response
func (o *GetWorkloadendpointBadRequest) SetPayload(payload models.Error) {
	_ = "STUB: not implemented"
	return

	// WriteResponse to the client
}

func (o *GetWorkloadendpointBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this

// GetWorkloadendpointNotFoundCode is the HTTP code returned for type GetWorkloadendpointNotFound
const GetWorkloadendpointNotFoundCode int = 404

/*
GetWorkloadendpointNotFound SpiderEndpoint not found for specified Pod

swagger:response getWorkloadendpointNotFound
*/
type GetWorkloadendpointNotFound struct {

	/*
	  In: Body
	*/
	Payload models.Error `json:"body,omitempty"`
}

// NewGetWorkloadendpointNotFound creates GetWorkloadendpointNotFound with default headers values
func NewGetWorkloadendpointNotFound() *GetWorkloadendpointNotFound {
	_ = "STUB: not implemented"
	return nil
}

// WithPayload adds the payload to the get workloadendpoint not found response
func (o *GetWorkloadendpointNotFound) WithPayload(payload models.Error) *GetWorkloadendpointNotFound {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the get workloadendpoint not found response
func (o *GetWorkloadendpointNotFound) SetPayload(payload models.Error) {
	_ = "STUB: not implemented"
	return

	// WriteResponse to the client
}

func (o *GetWorkloadendpointNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this

// GetWorkloadendpointInternalServerErrorCode is the HTTP code returned for type GetWorkloadendpointInternalServerError
const GetWorkloadendpointInternalServerErrorCode int = 500

/*
GetWorkloadendpointInternalServerError Get workloadendpoint failure

swagger:response getWorkloadendpointInternalServerError
*/
type GetWorkloadendpointInternalServerError struct {

	/*
	  In: Body
	*/
	Payload models.Error `json:"body,omitempty"`
}

// NewGetWorkloadendpointInternalServerError creates GetWorkloadendpointInternalServerError with default headers values
func NewGetWorkloadendpointInternalServerError() *GetWorkloadendpointInternalServerError {
	_ = "STUB: not implemented"
	return nil
}

// WithPayload adds the payload to the get workloadendpoint internal server error response
func (o *GetWorkloadendpointInternalServerError) WithPayload(payload models.Error) *GetWorkloadendpointInternalServerError {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the get workloadendpoint internal server error response
func (o *GetWorkloadendpointInternalServerError) SetPayload(payload models.Error) {
	_ = "STUB: not implemented"
	return

	// WriteResponse to the client
}

func (o *GetWorkloadendpointInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this
