// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package daemonset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetCoordinatorConfigHandlerFunc turns a function with the right signature into a get coordinator config handler
type GetCoordinatorConfigHandlerFunc func(GetCoordinatorConfigParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCoordinatorConfigHandlerFunc) Handle(params GetCoordinatorConfigParams) middleware.Responder {
	_ = "STUB: not implemented"

	// GetCoordinatorConfigHandler interface for that can handle valid get coordinator config params
	return *new(middleware.Responder)
}

type GetCoordinatorConfigHandler interface {
	Handle(GetCoordinatorConfigParams) middleware.Responder
}

// NewGetCoordinatorConfig creates a new http.Handler for the get coordinator config operation
func NewGetCoordinatorConfig(ctx *middleware.Context, handler GetCoordinatorConfigHandler) *GetCoordinatorConfig {
	_ = "STUB: not implemented"
	return nil
}

/*
	GetCoordinatorConfig swagger:route GET /coordinator/config daemonset getCoordinatorConfig

# Get coordinator config

Send a request to daemonset to get coordinator config
*/
type GetCoordinatorConfig struct {
	Context *middleware.Context
	Handler GetCoordinatorConfigHandler
}

func (o *GetCoordinatorConfig) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// bind params

// actually handle the request
