// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package daemonset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/spidernet-io/spiderpool/api/v1/agent/models"
)

// PostIpamIPOKCode is the HTTP code returned for type PostIpamIPOK
const PostIpamIPOKCode int = 200

/*
PostIpamIPOK Success

swagger:response postIpamIpOK
*/
type PostIpamIPOK struct {

	/*
	  In: Body
	*/
	Payload *models.IpamAddResponse `json:"body,omitempty"`
}

// NewPostIpamIPOK creates PostIpamIPOK with default headers values
func NewPostIpamIPOK() *PostIpamIPOK { _ = "STUB: not implemented"; return nil }

// WithPayload adds the payload to the post ipam Ip o k response
func (o *PostIpamIPOK) WithPayload(payload *models.IpamAddResponse) *PostIpamIPOK {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the post ipam Ip o k response
func (o *PostIpamIPOK) SetPayload(payload *models.IpamAddResponse) {
	_ = "STUB: not implemented"
	return

	// WriteResponse to the client
}

func (o *PostIpamIPOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this

// PostIpamIPFailureCode is the HTTP code returned for type PostIpamIPFailure
const PostIpamIPFailureCode int = 500

/*
PostIpamIPFailure Allocation failure

swagger:response postIpamIpFailure
*/
type PostIpamIPFailure struct {

	/*
	  In: Body
	*/
	Payload models.Error `json:"body,omitempty"`
}

// NewPostIpamIPFailure creates PostIpamIPFailure with default headers values
func NewPostIpamIPFailure() *PostIpamIPFailure { _ = "STUB: not implemented"; return nil }

// WithPayload adds the payload to the post ipam Ip failure response
func (o *PostIpamIPFailure) WithPayload(payload models.Error) *PostIpamIPFailure {
	_ = "STUB: not implemented"
	return nil
}

// SetPayload sets the payload to the post ipam Ip failure response
func (o *PostIpamIPFailure) SetPayload(payload models.Error) { _ = "STUB: not implemented"; return }

// WriteResponse to the client
func (o *PostIpamIPFailure) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

// let the recovery middleware deal with this
