// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetIpamStatusHandlerFunc turns a function with the right signature into a get ipam status handler
type GetIpamStatusHandlerFunc func(GetIpamStatusParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetIpamStatusHandlerFunc) Handle(params GetIpamStatusParams) middleware.Responder {
	_ = "STUB: not implemented"

	// GetIpamStatusHandler interface for that can handle valid get ipam status params
	return *new(middleware.Responder)
}

type GetIpamStatusHandler interface {
	Handle(GetIpamStatusParams) middleware.Responder
}

// NewGetIpamStatus creates a new http.Handler for the get ipam status operation
func NewGetIpamStatus(ctx *middleware.Context, handler GetIpamStatusHandler) *GetIpamStatus {
	_ = "STUB: not implemented"
	return nil
}

/*
	GetIpamStatus swagger:route GET /ipam/status controller getIpamStatus

# Get status

Get ipam status for spiderpool controller cli debug usage
*/
type GetIpamStatus struct {
	Context *middleware.Context
	Handler GetIpamStatusHandler
}

func (o *GetIpamStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// bind params

// actually handle the request
