// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/url"
)

// PostIpamGcIpsURL generates an URL for the post ipam gc ips operation
type PostIpamGcIpsURL struct {
	_basePath string
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *PostIpamGcIpsURL) WithBasePath(bp string) *PostIpamGcIpsURL {
	_ = "STUB: not implemented"
	return nil
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *PostIpamGcIpsURL) SetBasePath(bp string) {
	_ = "STUB: not implemented"

	// Build a url path and query string
	return
}

func (o *PostIpamGcIpsURL) Build() (*url.URL, error) { _ = "STUB: not implemented"; return nil, nil }

// Must is a helper function to panic when the url builder returns an error
func (o *PostIpamGcIpsURL) Must(u *url.URL, err error) *url.URL {
	_ = "STUB: not implemented"
	return nil
}

// String returns the string representation of the path with query string
func (o *PostIpamGcIpsURL) String() string { _ = "STUB: not implemented"; return "" }

// BuildFull builds a full url with scheme, host, path and query string
func (o *PostIpamGcIpsURL) BuildFull(scheme, host string) (*url.URL, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// StringFull returns the string representation of a complete url
func (o *PostIpamGcIpsURL) StringFull(scheme, host string) string {
	_ = "STUB: not implemented"
	return ""
}
