// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutIpamIPHandlerFunc turns a function with the right signature into a put ipam IP handler
type PutIpamIPHandlerFunc func(PutIpamIPParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutIpamIPHandlerFunc) Handle(params PutIpamIPParams) middleware.Responder {
	_ = "STUB: not implemented"

	// PutIpamIPHandler interface for that can handle valid put ipam IP params
	return *new(middleware.Responder)
}

type PutIpamIPHandler interface {
	Handle(PutIpamIPParams) middleware.Responder
}

// NewPutIpamIP creates a new http.Handler for the put ipam IP operation
func NewPutIpamIP(ctx *middleware.Context, handler PutIpamIPHandler) *PutIpamIP {
	_ = "STUB: not implemented"
	return nil
}

/*
	PutIpamIP swagger:route PUT /ipam/ip controller putIpamIp

# Force set ip

Force set ip for spiderpool controller cli debug usage
*/
type PutIpamIP struct {
	Context *middleware.Context
	Handler PutIpamIPHandler
}

func (o *PutIpamIP) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// bind params

// actually handle the request
