// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package runtime

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetRuntimeReadinessOKCode is the HTTP code returned for type GetRuntimeReadinessOK
const GetRuntimeReadinessOKCode int = 200

/*
GetRuntimeReadinessOK Success

swagger:response getRuntimeReadinessOK
*/
type GetRuntimeReadinessOK struct {
}

// NewGetRuntimeReadinessOK creates GetRuntimeReadinessOK with default headers values
func NewGetRuntimeReadinessOK() *GetRuntimeReadinessOK { _ = "STUB: not implemented"; return nil }

// WriteResponse to the client
func (o *GetRuntimeReadinessOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

//Remove Content-Type on empty responses

// GetRuntimeReadinessInternalServerErrorCode is the HTTP code returned for type GetRuntimeReadinessInternalServerError
const GetRuntimeReadinessInternalServerErrorCode int = 500

/*
GetRuntimeReadinessInternalServerError Failed

swagger:response getRuntimeReadinessInternalServerError
*/
type GetRuntimeReadinessInternalServerError struct {
}

// NewGetRuntimeReadinessInternalServerError creates GetRuntimeReadinessInternalServerError with default headers values
func NewGetRuntimeReadinessInternalServerError() *GetRuntimeReadinessInternalServerError {
	_ = "STUB: not implemented"
	return nil
}

// WriteResponse to the client
func (o *GetRuntimeReadinessInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	_ = "STUB: not implemented"
	return
}

//Remove Content-Type on empty responses
