// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package runtime

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetRuntimeReadinessHandlerFunc turns a function with the right signature into a get runtime readiness handler
type GetRuntimeReadinessHandlerFunc func(GetRuntimeReadinessParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRuntimeReadinessHandlerFunc) Handle(params GetRuntimeReadinessParams) middleware.Responder {
	_ = "STUB: not implemented"

	// GetRuntimeReadinessHandler interface for that can handle valid get runtime readiness params
	return *new(middleware.Responder)
}

type GetRuntimeReadinessHandler interface {
	Handle(GetRuntimeReadinessParams) middleware.Responder
}

// NewGetRuntimeReadiness creates a new http.Handler for the get runtime readiness operation
func NewGetRuntimeReadiness(ctx *middleware.Context, handler GetRuntimeReadinessHandler) *GetRuntimeReadiness {
	_ = "STUB: not implemented"
	return nil
}

/*
	GetRuntimeReadiness swagger:route GET /runtime/readiness runtime getRuntimeReadiness

# Readiness probe

Check pod readiness probe
*/
type GetRuntimeReadiness struct {
	Context *middleware.Context
	Handler GetRuntimeReadinessHandler
}

func (o *GetRuntimeReadiness) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	_ = "STUB: not implemented"
	return
}

// bind params

// actually handle the request
