// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by informer-gen. DO NOT EDIT.

package v2beta1

import (
	internalinterfaces "github.com/spidernet-io/spiderpool/pkg/k8s/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// SpiderCoordinators returns a SpiderCoordinatorInformer.
	SpiderCoordinators() SpiderCoordinatorInformer
	// SpiderIPPools returns a SpiderIPPoolInformer.
	SpiderIPPools() SpiderIPPoolInformer
	// SpiderMultusConfigs returns a SpiderMultusConfigInformer.
	SpiderMultusConfigs() SpiderMultusConfigInformer
	// SpiderSubnets returns a SpiderSubnetInformer.
	SpiderSubnets() SpiderSubnetInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	_ = "STUB: not implemented"
	return *new(Interface)
}

// SpiderCoordinators returns a SpiderCoordinatorInformer.
func (v *version) SpiderCoordinators() SpiderCoordinatorInformer {
	_ = "STUB: not implemented"
	return *new(SpiderCoordinatorInformer)
}

// SpiderIPPools returns a SpiderIPPoolInformer.
func (v *version) SpiderIPPools() SpiderIPPoolInformer {
	_ = "STUB: not implemented"
	return *new(SpiderIPPoolInformer)
}

// SpiderMultusConfigs returns a SpiderMultusConfigInformer.
func (v *version) SpiderMultusConfigs() SpiderMultusConfigInformer {
	_ = "STUB: not implemented"
	return *new(SpiderMultusConfigInformer)
}

// SpiderSubnets returns a SpiderSubnetInformer.
func (v *version) SpiderSubnets() SpiderSubnetInformer {
	_ = "STUB: not implemented"
	return *new(SpiderSubnetInformer)
}
