// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by MockGen. DO NOT EDIT.
// Source: ./reservedip_manager.go

// Package mock_reservedipmanager is a generated GoMock package.
package mock_reservedipmanager

import (
	context "context"
	net "net"

	gomock "github.com/golang/mock/gomock"
	v2beta1 "github.com/spidernet-io/spiderpool/pkg/k8s/apis/spiderpool.spidernet.io/v2beta1"
	types "github.com/spidernet-io/spiderpool/pkg/types"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockReservedIPManager is a mock of ReservedIPManager interface.
type MockReservedIPManager struct {
	ctrl     *gomock.Controller
	recorder *MockReservedIPManagerMockRecorder
}

// MockReservedIPManagerMockRecorder is the mock recorder for MockReservedIPManager.
type MockReservedIPManagerMockRecorder struct {
	mock *MockReservedIPManager
}

// NewMockReservedIPManager creates a new mock instance.
func NewMockReservedIPManager(ctrl *gomock.Controller) *MockReservedIPManager {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReservedIPManager) EXPECT() *MockReservedIPManagerMockRecorder {
	_ = "STUB: not implemented"

	// AssembleReservedIPs mocks base method.
	return nil
}

func (m *MockReservedIPManager) AssembleReservedIPs(ctx context.Context, version types.IPVersion) ([]net.IP, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AssembleReservedIPs indicates an expected call of AssembleReservedIPs.
func (mr *MockReservedIPManagerMockRecorder) AssembleReservedIPs(ctx, version interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetReservedIPByName mocks base method.
func (m *MockReservedIPManager) GetReservedIPByName(ctx context.Context, rIPName string, cached bool) (*v2beta1.SpiderReservedIP, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetReservedIPByName indicates an expected call of GetReservedIPByName.
func (mr *MockReservedIPManagerMockRecorder) GetReservedIPByName(ctx, rIPName, cached interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListReservedIPs mocks base method.
func (m *MockReservedIPManager) ListReservedIPs(ctx context.Context, cached bool, opts ...client.ListOption) (*v2beta1.SpiderReservedIPList, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListReservedIPs indicates an expected call of ListReservedIPs.
func (mr *MockReservedIPManagerMockRecorder) ListReservedIPs(ctx, cached interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
