// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v2beta1

import (
	"net/http"

	rest "k8s.io/client-go/rest"
)

type SpiderpoolV2beta1Interface interface {
	RESTClient() rest.Interface
	SpiderCoordinatorsGetter
	SpiderIPPoolsGetter
	SpiderMultusConfigsGetter
	SpiderSubnetsGetter
}

// SpiderpoolV2beta1Client is used to interact with features provided by the spiderpool.spidernet.io group.
type SpiderpoolV2beta1Client struct {
	restClient rest.Interface
}

func (c *SpiderpoolV2beta1Client) SpiderCoordinators() SpiderCoordinatorInterface {
	_ = "STUB: not implemented"
	return *new(SpiderCoordinatorInterface)
}

func (c *SpiderpoolV2beta1Client) SpiderIPPools() SpiderIPPoolInterface {
	_ = "STUB: not implemented"
	return *new(SpiderIPPoolInterface)
}

func (c *SpiderpoolV2beta1Client) SpiderMultusConfigs(namespace string) SpiderMultusConfigInterface {
	_ = "STUB: not implemented"
	return *new(SpiderMultusConfigInterface)
}

func (c *SpiderpoolV2beta1Client) SpiderSubnets() SpiderSubnetInterface {
	_ = "STUB: not implemented"
	return *new(SpiderSubnetInterface)
}

// NewForConfig creates a new SpiderpoolV2beta1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*SpiderpoolV2beta1Client, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewForConfigAndClient creates a new SpiderpoolV2beta1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*SpiderpoolV2beta1Client, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NewForConfigOrDie creates a new SpiderpoolV2beta1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *SpiderpoolV2beta1Client {
	_ = "STUB: not implemented"
	return nil
}

// New creates a new SpiderpoolV2beta1Client for the given RESTClient.
func New(c rest.Interface) *SpiderpoolV2beta1Client { _ = "STUB: not implemented"; return nil }

func setConfigDefaults(config *rest.Config) error { _ = "STUB: not implemented"; return nil }

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *SpiderpoolV2beta1Client) RESTClient() rest.Interface {
	_ = "STUB: not implemented"
	return *new(rest.Interface)
}
