// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v2beta1

import (
	"context"

	v2beta1 "github.com/spidernet-io/spiderpool/pkg/k8s/apis/spiderpool.spidernet.io/v2beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SpiderSubnetsGetter has a method to return a SpiderSubnetInterface.
// A group's client should implement this interface.
type SpiderSubnetsGetter interface {
	SpiderSubnets() SpiderSubnetInterface
}

// SpiderSubnetInterface has methods to work with SpiderSubnet resources.
type SpiderSubnetInterface interface {
	Create(ctx context.Context, spiderSubnet *v2beta1.SpiderSubnet, opts v1.CreateOptions) (*v2beta1.SpiderSubnet, error)
	Update(ctx context.Context, spiderSubnet *v2beta1.SpiderSubnet, opts v1.UpdateOptions) (*v2beta1.SpiderSubnet, error)
	UpdateStatus(ctx context.Context, spiderSubnet *v2beta1.SpiderSubnet, opts v1.UpdateOptions) (*v2beta1.SpiderSubnet, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v2beta1.SpiderSubnet, error)
	List(ctx context.Context, opts v1.ListOptions) (*v2beta1.SpiderSubnetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2beta1.SpiderSubnet, err error)
	SpiderSubnetExpansion
}

// spiderSubnets implements SpiderSubnetInterface
type spiderSubnets struct {
	client rest.Interface
}

// newSpiderSubnets returns a SpiderSubnets
func newSpiderSubnets(c *SpiderpoolV2beta1Client) *spiderSubnets {
	_ = "STUB: not implemented"
	return nil
}

// Get takes name of the spiderSubnet, and returns the corresponding spiderSubnet object, and an error if there is any.
func (c *spiderSubnets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2beta1.SpiderSubnet, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// List takes label and field selectors, and returns the list of SpiderSubnets that match those selectors.
func (c *spiderSubnets) List(ctx context.Context, opts v1.ListOptions) (result *v2beta1.SpiderSubnetList, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Watch returns a watch.Interface that watches the requested spiderSubnets.
func (c *spiderSubnets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	_ = "STUB: not implemented"
	return *new(watch.Interface), nil
}

// Create takes the representation of a spiderSubnet and creates it.  Returns the server's representation of the spiderSubnet, and an error, if there is any.
func (c *spiderSubnets) Create(ctx context.Context, spiderSubnet *v2beta1.SpiderSubnet, opts v1.CreateOptions) (result *v2beta1.SpiderSubnet, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Update takes the representation of a spiderSubnet and updates it. Returns the server's representation of the spiderSubnet, and an error, if there is any.
func (c *spiderSubnets) Update(ctx context.Context, spiderSubnet *v2beta1.SpiderSubnet, opts v1.UpdateOptions) (result *v2beta1.SpiderSubnet, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *spiderSubnets) UpdateStatus(ctx context.Context, spiderSubnet *v2beta1.SpiderSubnet, opts v1.UpdateOptions) (result *v2beta1.SpiderSubnet, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Delete takes name of the spiderSubnet and deletes it. Returns an error if one occurs.
func (c *spiderSubnets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteCollection deletes a collection of objects.
func (c *spiderSubnets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// Patch applies the patch and returns the patched spiderSubnet.
func (c *spiderSubnets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2beta1.SpiderSubnet, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}
