// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v2beta1

import (
	"context"

	v2beta1 "github.com/spidernet-io/spiderpool/pkg/k8s/apis/spiderpool.spidernet.io/v2beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SpiderIPPoolsGetter has a method to return a SpiderIPPoolInterface.
// A group's client should implement this interface.
type SpiderIPPoolsGetter interface {
	SpiderIPPools() SpiderIPPoolInterface
}

// SpiderIPPoolInterface has methods to work with SpiderIPPool resources.
type SpiderIPPoolInterface interface {
	Create(ctx context.Context, spiderIPPool *v2beta1.SpiderIPPool, opts v1.CreateOptions) (*v2beta1.SpiderIPPool, error)
	Update(ctx context.Context, spiderIPPool *v2beta1.SpiderIPPool, opts v1.UpdateOptions) (*v2beta1.SpiderIPPool, error)
	UpdateStatus(ctx context.Context, spiderIPPool *v2beta1.SpiderIPPool, opts v1.UpdateOptions) (*v2beta1.SpiderIPPool, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v2beta1.SpiderIPPool, error)
	List(ctx context.Context, opts v1.ListOptions) (*v2beta1.SpiderIPPoolList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2beta1.SpiderIPPool, err error)
	SpiderIPPoolExpansion
}

// spiderIPPools implements SpiderIPPoolInterface
type spiderIPPools struct {
	client rest.Interface
}

// newSpiderIPPools returns a SpiderIPPools
func newSpiderIPPools(c *SpiderpoolV2beta1Client) *spiderIPPools {
	_ = "STUB: not implemented"
	return nil
}

// Get takes name of the spiderIPPool, and returns the corresponding spiderIPPool object, and an error if there is any.
func (c *spiderIPPools) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2beta1.SpiderIPPool, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// List takes label and field selectors, and returns the list of SpiderIPPools that match those selectors.
func (c *spiderIPPools) List(ctx context.Context, opts v1.ListOptions) (result *v2beta1.SpiderIPPoolList, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Watch returns a watch.Interface that watches the requested spiderIPPools.
func (c *spiderIPPools) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	_ = "STUB: not implemented"
	return *new(watch.Interface), nil
}

// Create takes the representation of a spiderIPPool and creates it.  Returns the server's representation of the spiderIPPool, and an error, if there is any.
func (c *spiderIPPools) Create(ctx context.Context, spiderIPPool *v2beta1.SpiderIPPool, opts v1.CreateOptions) (result *v2beta1.SpiderIPPool, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Update takes the representation of a spiderIPPool and updates it. Returns the server's representation of the spiderIPPool, and an error, if there is any.
func (c *spiderIPPools) Update(ctx context.Context, spiderIPPool *v2beta1.SpiderIPPool, opts v1.UpdateOptions) (result *v2beta1.SpiderIPPool, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *spiderIPPools) UpdateStatus(ctx context.Context, spiderIPPool *v2beta1.SpiderIPPool, opts v1.UpdateOptions) (result *v2beta1.SpiderIPPool, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Delete takes name of the spiderIPPool and deletes it. Returns an error if one occurs.
func (c *spiderIPPools) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteCollection deletes a collection of objects.
func (c *spiderIPPools) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// Patch applies the patch and returns the patched spiderIPPool.
func (c *spiderIPPools) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2beta1.SpiderIPPool, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}
