// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// CoordinatorConfig Coordinator config
//
// swagger:model CoordinatorConfig
type CoordinatorConfig struct {

	// hijack c ID r
	HijackCIDR []string `json:"hijackCIDR"`

	// host rule table
	HostRuleTable int64 `json:"hostRuleTable,omitempty"`

	// mode
	// Required: true
	Mode *string `json:"mode"`

	// overlay pod c ID r
	// Required: true
	OverlayPodCIDR []string `json:"overlayPodCIDR"`

	// pod default route n i c
	PodDefaultRouteNIC string `json:"podDefaultRouteNIC,omitempty"`

	// pod m a c prefix
	PodMACPrefix string `json:"podMACPrefix,omitempty"`

	// pod r p filter
	PodRPFilter int64 `json:"podRPFilter,omitempty"`

	// service c ID r
	// Required: true
	ServiceCIDR []string `json:"serviceCIDR"`

	// tune pod routes
	// Required: true
	TunePodRoutes *bool `json:"tunePodRoutes"`

	// tx queue len
	TxQueueLen int64 `json:"txQueueLen,omitempty"`

	// veth link address
	VethLinkAddress string `json:"vethLinkAddress,omitempty"`
}

// Validate validates this coordinator config
func (m *CoordinatorConfig) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *CoordinatorConfig) validateMode(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *CoordinatorConfig) validateOverlayPodCIDR(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *CoordinatorConfig) validateServiceCIDR(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *CoordinatorConfig) validateTunePodRoutes(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// ContextValidate validates this coordinator config based on context it is used
func (m *CoordinatorConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// MarshalBinary interface implementation
	return nil
}

func (m *CoordinatorConfig) MarshalBinary() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary interface implementation
func (m *CoordinatorConfig) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
