// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// DNS IPAM CNI types DNS
//
// swagger:model DNS
type DNS struct {

	// domain
	Domain string `json:"domain,omitempty"`

	// nameservers
	Nameservers []string `json:"nameservers"`

	// options
	Options []string `json:"options"`

	// search
	Search []string `json:"search"`
}

// Validate validates this DNS
func (m *DNS) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// ContextValidate validates this DNS based on context it is used
	return nil
}

func (m *DNS) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// MarshalBinary interface implementation
	return nil
}

func (m *DNS) MarshalBinary() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalBinary interface implementation
func (m *DNS) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
