// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// GetCoordinatorArgs Get Coordinator Args
//
// swagger:model GetCoordinatorArgs
type GetCoordinatorArgs struct {

	// pod name
	PodName string `json:"podName,omitempty"`

	// pod namespace
	PodNamespace string `json:"podNamespace,omitempty"`
}

// Validate validates this get coordinator args
func (m *GetCoordinatorArgs) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// ContextValidate validates this get coordinator args based on context it is used
	return nil
}

func (m *GetCoordinatorArgs) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// MarshalBinary interface implementation
	return nil
}

func (m *GetCoordinatorArgs) MarshalBinary() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary interface implementation
func (m *GetCoordinatorArgs) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
