// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// InterfaceDetail Network interface allocation details
//
// swagger:model InterfaceDetail
type InterfaceDetail struct {

	// Interface name (e.g., "eth0", "net1")
	// Required: true
	Interface *string `json:"interface"`

	// IPv4 address with CIDR (e.g., "10.244.1.10/24")
	IPV4 string `json:"ipv4,omitempty"`

	// IPv4 gateway address
	IPV4Gateway string `json:"ipv4Gateway,omitempty"`

	// Source IPv4 IPPool name
	IPV4Pool string `json:"ipv4Pool,omitempty"`

	// IPv6 address with CIDR (e.g., "fd00:10:244::10/64")
	IPV6 string `json:"ipv6,omitempty"`

	// IPv6 gateway address
	IPV6Gateway string `json:"ipv6Gateway,omitempty"`

	// Source IPv6 IPPool name
	IPV6Pool string `json:"ipv6Pool,omitempty"`

	// MAC address (e.g., "aa:bb:cc:dd:ee:ff"). Optional.
	// Pattern: ^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$
	Mac string `json:"mac,omitempty"`

	// Static routes
	Routes []*Route `json:"routes"`

	// VLAN ID. Optional.
	Vlan int64 `json:"vlan,omitempty"`
}

// Validate validates this interface detail
func (m *InterfaceDetail) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *InterfaceDetail) validateInterface(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *InterfaceDetail) validateMac(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
	// not required
}

func (m *InterfaceDetail) validateRoutes(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
	// not required
}

// not required

// ContextValidate validate this interface detail based on the context it is used
func (m *InterfaceDetail) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *InterfaceDetail) contextValidateRoutes(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalBinary interface implementation
func (m *InterfaceDetail) MarshalBinary() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary interface implementation
func (m *InterfaceDetail) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
