// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/strfmt"
)

// IPConfig IPAM IPs struct, contains ifName, Address and Gateway
//
// swagger:model IpConfig
type IPConfig struct {

	// address
	// Required: true
	Address *string `json:"address"`

	// enable gateway detection
	EnableGatewayDetection bool `json:"enableGatewayDetection,omitempty"`

	// enable IP conflict detection
	EnableIPConflictDetection bool `json:"enableIPConflictDetection,omitempty"`

	// gateway
	Gateway string `json:"gateway,omitempty"`

	// ip pool
	IPPool string `json:"ipPool,omitempty"`

	// MAC address (optional, provided by external systems)
	// Pattern: ^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$
	Mac string `json:"mac,omitempty"`

	// nic
	// Required: true
	Nic *string `json:"nic"`

	// version
	// Required: true
	// Enum: [4 6]
	Version *int64 `json:"version"`

	// vlan
	Vlan int64 `json:"vlan,omitempty"`
}

// Validate validates this Ip config
func (m *IPConfig) Validate(formats strfmt.Registry) error { _ = "STUB: not implemented"; return nil }

func (m *IPConfig) validateAddress(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *IPConfig) validateMac(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
	// not required
}

func (m *IPConfig) validateNic(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

var ipConfigTypeVersionPropEnum []interface{}

func init() {
	var res []int64
	if err := json.Unmarshal([]byte(`[4,6]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		ipConfigTypeVersionPropEnum = append(ipConfigTypeVersionPropEnum, v)
	}
}

// prop value enum
func (m *IPConfig) validateVersionEnum(path, location string, value int64) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *IPConfig) validateVersion(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// value enum

// ContextValidate validates this Ip config based on context it is used
func (m *IPConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// MarshalBinary interface implementation
	return nil
}

func (m *IPConfig) MarshalBinary() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalBinary interface implementation
func (m *IPConfig) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
