// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// IpamDelArgs IPAM release IP information
//
// swagger:model IpamDelArgs
type IpamDelArgs struct {

	// container ID
	// Required: true
	ContainerID *string `json:"containerID"`

	// if name
	// Required: true
	IfName *string `json:"ifName"`

	// net namespace
	NetNamespace string `json:"netNamespace,omitempty"`

	// pod name
	// Required: true
	PodName *string `json:"podName"`

	// pod namespace
	// Required: true
	PodNamespace *string `json:"podNamespace"`

	// pod UID
	// Required: true
	PodUID *string `json:"podUID"`
}

// Validate validates this ipam del args
func (m *IpamDelArgs) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *IpamDelArgs) validateContainerID(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *IpamDelArgs) validateIfName(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *IpamDelArgs) validatePodName(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *IpamDelArgs) validatePodNamespace(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *IpamDelArgs) validatePodUID(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// ContextValidate validates this ipam del args based on context it is used
func (m *IpamDelArgs) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// MarshalBinary interface implementation
	return nil
}

func (m *IpamDelArgs) MarshalBinary() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalBinary interface implementation
func (m *IpamDelArgs) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
