// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// IpamBatchDelArgs IPAM release IPs information
//
// swagger:model IpamBatchDelArgs
type IpamBatchDelArgs struct {

	// container ID
	// Required: true
	ContainerID *string `json:"containerID"`

	// is release conflict i ps
	IsReleaseConflictIPs bool `json:"isReleaseConflictIPs,omitempty"`

	// net namespace
	NetNamespace string `json:"netNamespace,omitempty"`

	// pod name
	// Required: true
	PodName *string `json:"podName"`

	// pod namespace
	// Required: true
	PodNamespace *string `json:"podNamespace"`

	// pod UID
	// Required: true
	PodUID *string `json:"podUID"`
}

// Validate validates this ipam batch del args
func (m *IpamBatchDelArgs) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *IpamBatchDelArgs) validateContainerID(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *IpamBatchDelArgs) validatePodName(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *IpamBatchDelArgs) validatePodNamespace(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *IpamBatchDelArgs) validatePodUID(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// ContextValidate validates this ipam batch del args based on context it is used
func (m *IpamBatchDelArgs) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// MarshalBinary interface implementation
	return nil
}

func (m *IpamBatchDelArgs) MarshalBinary() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary interface implementation
func (m *IpamBatchDelArgs) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
