// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// IpamAddResponse IPAM assignment IPs information
//
// swagger:model IpamAddResponse
type IpamAddResponse struct {

	// dns
	DNS *DNS `json:"dns,omitempty"`

	// ips
	// Required: true
	Ips []*IPConfig `json:"ips"`

	// routes
	Routes []*Route `json:"routes"`
}

// Validate validates this ipam add response
func (m *IpamAddResponse) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *IpamAddResponse) validateDNS(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
	// not required
}

func (m *IpamAddResponse) validateIps(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required

func (m *IpamAddResponse) validateRoutes(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
	// not required
}

// not required

// ContextValidate validate this ipam add response based on the context it is used
func (m *IpamAddResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *IpamAddResponse) contextValidateDNS(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *IpamAddResponse) contextValidateIps(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *IpamAddResponse) contextValidateRoutes(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalBinary interface implementation
func (m *IpamAddResponse) MarshalBinary() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary interface implementation
func (m *IpamAddResponse) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
