// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// IpamAddArgs IPAM request args
//
// swagger:model IpamAddArgs
type IpamAddArgs struct {

	// clean gateway
	CleanGateway bool `json:"cleanGateway,omitempty"`

	// container ID
	// Required: true
	ContainerID *string `json:"containerID"`

	// default IPv4 IP pool
	DefaultIPV4IPPool []string `json:"defaultIPv4IPPool"`

	// default IPv6 IP pool
	DefaultIPV6IPPool []string `json:"defaultIPv6IPPool"`

	// if name
	// Required: true
	IfName *string `json:"ifName"`

	// match master subnet
	MatchMasterSubnet bool `json:"matchMasterSubnet,omitempty"`

	// net namespace
	// Required: true
	NetNamespace *string `json:"netNamespace"`

	// pod name
	// Required: true
	PodName *string `json:"podName"`

	// pod namespace
	// Required: true
	PodNamespace *string `json:"podNamespace"`

	// pod UID
	// Required: true
	PodUID *string `json:"podUID"`
}

// Validate validates this ipam add args
func (m *IpamAddArgs) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *IpamAddArgs) validateContainerID(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *IpamAddArgs) validateIfName(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *IpamAddArgs) validateNetNamespace(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *IpamAddArgs) validatePodName(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *IpamAddArgs) validatePodNamespace(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *IpamAddArgs) validatePodUID(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// ContextValidate validates this ipam add args based on context it is used
func (m *IpamAddArgs) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// MarshalBinary interface implementation
	return nil
}

func (m *IpamAddArgs) MarshalBinary() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalBinary interface implementation
func (m *IpamAddArgs) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
