// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// Route IPAM CNI types Route
//
// swagger:model Route
type Route struct {

	// dst
	// Required: true
	Dst *string `json:"dst"`

	// gw
	// Required: true
	Gw *string `json:"gw"`

	// if name
	// Required: true
	IfName *string `json:"ifName"`
}

// Validate validates this route
func (m *Route) Validate(formats strfmt.Registry) error { _ = "STUB: not implemented"; return nil }

func (m *Route) validateDst(formats strfmt.Registry) error { _ = "STUB: not implemented"; return nil }

func (m *Route) validateGw(formats strfmt.Registry) error { _ = "STUB: not implemented"; return nil }

func (m *Route) validateIfName(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// ContextValidate validates this route based on context it is used
func (m *Route) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"

	// MarshalBinary interface implementation
	return nil
}

func (m *Route) MarshalBinary() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

// UnmarshalBinary interface implementation
func (m *Route) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }
