// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// WorkloadEndpointStatus Pod network allocation status
//
// swagger:model WorkloadEndpointStatus
type WorkloadEndpointStatus struct {

	// List of network interfaces
	// Required: true
	Interfaces []*InterfaceDetail `json:"interfaces"`

	// Node name where Pod is running
	// Required: true
	Node *string `json:"node"`

	// Pod name
	// Required: true
	PodName *string `json:"podName"`

	// Pod namespace
	// Required: true
	PodNamespace *string `json:"podNamespace"`

	// Pod unique identifier
	// Required: true
	PodUID *string `json:"podUID"`
}

// Validate validates this workload endpoint status
func (m *WorkloadEndpointStatus) Validate(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *WorkloadEndpointStatus) validateInterfaces(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// not required

func (m *WorkloadEndpointStatus) validateNode(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *WorkloadEndpointStatus) validatePodName(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *WorkloadEndpointStatus) validatePodNamespace(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *WorkloadEndpointStatus) validatePodUID(formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// ContextValidate validate this workload endpoint status based on the context it is used
func (m *WorkloadEndpointStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

func (m *WorkloadEndpointStatus) contextValidateInterfaces(ctx context.Context, formats strfmt.Registry) error {
	_ = "STUB: not implemented"
	return nil
}

// MarshalBinary interface implementation
func (m *WorkloadEndpointStatus) MarshalBinary() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary interface implementation
func (m *WorkloadEndpointStatus) UnmarshalBinary(b []byte) error {
	_ = "STUB: not implemented"
	return nil
}
